### ISSUE TITLE
Can't stage 0.12.0 or 0.13.0 for Beam/Dataflow usage due to missing pyarrow 0.11.1 source release

### ISSUE THREAD

**Issue by ryan-williams** [tensorflow/transform#102]
TFT 0.12.0 and 0.13.0 depend on Beam 2.10.0 and 2.11.0, resp., which both [depend on pyarrow 0.11.1](https://github.com/apache/beam/blob/v2.11.0/sdks/python/setup.py#L120).

When staging TFT for use on Dataflow worker nodes:

```
%%writefile requirements.txt
tensorflow-transform==0.13.0
```

Beam attempts to install TFT [source artifacts](https://github.com/apache/beam/blob/v2.11.0/sdks/python/apache_beam/runners/portability/stager.py#L423), but [pyarrow 0.11.1 sources aren't on pypi](https://github.com/apache/arrow/issues/3855), and it fails.

Is this a known issue?

xref: [BEAM-6765](https://issues.apache.org/jira/browse/BEAM-6765)

**Comment by ryan-williams** [comment]
Note that this effectively blocks [Python 3 usage](https://github.com/tensorflow/transform/issues/1), since Beam 2.11.0 is the only Py3-compatible Beam release.

**Comment by hgadig** [comment]
Thanks for reporting. It would be really good to track this in the single reference[ issue ](https://github.com/tensorflow/transform/issues/1) about Python 3 support.

**Comment by tvalentyn** [comment]
Commented on BEAM-6765

**Comment by ryan-williams** [comment]
The connection to Python 3 TFT was incidental. This affected TFT 0.12.0 and 0.13.0 on py2, unless I'm mistaken.

In any case, the arrow folks published 0.11.1 sources (closing https://github.com/apache/arrow/issues/3855), so I'm optimistic this is resolved, though haven't had a chance to test it yet.
