### ISSUE TITLE
Advanced transformers

### ISSUE THREAD

**Issue by HugoDLopes** [tensorflow/transform#103]
Hi, it's not still clear for me if the TFT can scale for more complex transformers. For instance:
* Missing Value Imputation
* Outliers detection and removal

If it is possible, what is the recommended way to proceed? Implement the above transformers using the core tft functions? 

Thanks for the explanation.

**Comment by cyc** [comment]
@HugoDLopes not sure exactly what you are trying to do, but you may want to look into the following:

* Missing Value Imputation: If there are missing values present in your data, your schema ought to reflect this and the resulting tensor that you will get for that feature will be a `tf.SparseTensor`. You can then use `tf.sparse.to_dense` with an appropriate `default_value` to impute a value in the dense representation. You can even use TFT to calculate the mean or median and use that as the default value.
* Outliers detection and removal: I'm not sure what specific outlier detection method you had in mind, but for instance if you wanted to cap your data at a certain z-score or percentile that is fairly easy to do with the built-in TFT methods.

**Comment by hgadig** [comment]
You can also take a look at the following [link](https://www.tensorflow.org/tfx/transform/api_docs/python/tft) which has the list of available functions for TFT.

**Comment by amarchin** [comment]
@cyc I am not sure to get it... what do you mean with "your schema ought to reflect this and the resulting tensor that you will get for that feature will be a tf.SparseTensor"?

**Comment by zoyahav** [comment]
@amarchin, a schema that reflects a feature with possibly missing values and results in a tf.SparseTensor is a schema that originates from a feature_spec that has an entry like this:
`{'x': tf.io.VarLenFeature(tf.float32), ...}`
as opposed to a tf.io.FixedLenFeature(..).

And in ml-metadata schema form it would be something like (note the presence field):
```
feature: {
  name: "x"
  presence: {
    min_fraction: 0
  }
  value_count: {
    min: 1
  }
  type: FLOAT
}
```
