### ISSUE TITLE
use_deep_copy_optimization can do weird things to your dataflow graph

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#112]
In my current workflow I apply several transformations to the input data in between `ReadFromTFRecord` and `AnalyzeAndTransformDataset`. For some reason enabling `use_deep_copy_optimization=True` seems to create an extra graph node that outputs to nowhere and I'm not sure why.

<img width="698" alt="Screen Shot 2019-04-10 at 11 51 40 PM" src="https://user-images.githubusercontent.com/1501289/55936743-0113e000-5bec-11e9-8db7-30d074e9fd47.png">

Note: without the `ImputeMissingWithDefault` step it works as expected, with one `ParDo` node for the original intermediate steps and one for the `Copy` step. But once I added `ImputeMissingWithDefault` it put 2 copies for some reason.

Job ID is `2019-04-10_03_50_39-2170621352903708737` if you are curious.

**Comment by zoyahav** [comment]
What does this graph look like when you expand the AnalyzeAndTransform stage?

Deep copy should re-do read and data transformations for 2+ phase analyzers (those that depend on the output of other analyzers), and for the Transform stage.
Is your preprocessing_fn configuring a multi phase analysis?

I'm trying to understand if this is WAI, a UI rendering bug, or an actual library bug.
(Note that we don't have access to your Dataflow jobs since we don't have access to your cloud project).

**Comment by cyc** [comment]
@zoyahav how deep do you want me to go in expanding `AnalyzeAndTransform`? Since we do a lot of transformations, if I expand the `Analyze` step it quickly blows up very large.

I don't think we are doing a multi-phase analysis. I think this is most likely due to that `ImputeMissingWithDefaults` node, because when I run it without that the graph looks fine (only one copy). And I suspect that this is due to the implementation of `ImputeMissingWithDefaults`, which is just a `beam.Map` of this function:

```python
def impute_univalent_with_default_value(example, default_values):
    imputed = default_values.copy()
    imputed.update({k: v for k, v in example.iteritems() if v is not None})
    return imputed
```

Where `default_values` is just a dictionary mapping feature names to the default value for their type/shape. Could something like this cause problems with `use_deep_copy_optimization`?

**Comment by zoyahav** [comment]
Unable to assign to @charlesccychen, so keeping this assigned to me for now.

**Comment by charlesccychen** [comment]
@cyc is it possible for you to provide a fresh job ID I can use to request access?  You can start and immediately cancel the job.

**Comment by cyc** [comment]
@charlesccychen try this one: `2019-05-20_17_44_16-5184493405357698238`

**Comment by charlesccychen** [comment]
This should have been fixed by https://github.com/tensorflow/transform/commit/033ef548464dec59f3d0d72140f5a51c07985820, but let me know if that is not the case.

**Comment by cyc** [comment]
@charlesccychen hmm, I just upgraded to TFT 0.15.0 and it still seems to be happening. Here is a job ID for a recent run: `2019-10-23_04_04_27-12998988382552634432`

**Comment by UsharaniPagadala** [comment]
@cyc 

Could you please confirm if this issue can be closed.Thanks

**Comment by cyc** [comment]
@UsharaniPagadala yes
