### ISSUE TITLE
Using Tensorflow Transform without using Tensorflow for training

### ISSUE THREAD

**Issue by srirampmalladi** [tensorflow/transform#114]
We would like to use Tensorflow Transform for our Feature Transformation step but use XGBoost to actually train our model. We ran TF transform on some tf.Examples that we’ve generated without performing any model training. When we inspected the resulting transformation graph, we noticed that there were three placeholders for each feature whose names were: 

- “inputs/feature-name/shape”
- “inputs/feature-name/values”
- “inputs/feature-name/indices”

When we run the same pipeline with a Tensorflow Training training component following the transformation, an additional placeholder is present in the resulting graph called:

- “input_example_tensor”

This placeholder is how we would feed tf.Examples into the combined transformation and prediction graph. However, it is unclear how we would feed our tf.Examples into just the transformation graph which does not have this placeholder. Is there a recommended strategy for feeding untransformed tf.Examples into a Tensorflow Transform graph, without a Tensorflow	 model involved, to get transformed features to input into our XGBoost model?

**Comment by KesterTong** [comment]
Are you able to share a sniped of code from your Training component?

It sounds to me like what you should be doing is creating a graph containing a tf.parse_example op, followed by TFTransformOutput.transform_raw_features to apply the graph.  Then you can call this graph in a session to transform your features.

**Comment by gowtham-kp** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
