### ISSUE TITLE
Can AnalyzeDataset/TransformDataset take metadata as a Singleton side-input?

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#115]
I'm currently struggling with an issue where I would like to pass in the input data metadata as a side-input to AnalyzeDataset or TransformDataset instead of as a fully-materialized DatasetMetadata instance. Is this possible to do?

**Comment by KesterTong** [comment]
It cannot because the Schema is used during graph construction.  In particular it is used to construct placeholders in the graph before calling `preprocessing_fn`.

**Comment by cyc** [comment]
That's what I was afraid of. OK, good to know that it is not possible to work around that.
