### ISSUE TITLE
Add C++ implementation of ExampleProtoCoder?

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#116]
TFDV 0.14 will have a C++ implementation of TFExampleDecoder, which on the dataset that I use (large number of scalar features), results in about an 7.5x speedup for decoding tf.Examples and a 2.25x speedup for running TFDV as a whole (see data [here](https://github.com/tensorflow/data-validation/issues/56#issuecomment-484245139)).

Likewise, in TFT there is the `ExampleProtoCoder`, which is used to decode/encode tf.Examples into beam examples (and vice versa). However, it is a pure python implementation. Will there be a C++ implementation of this coder coming soon?

**Comment by chanshah** [comment]
@cyc Thank you for raising this and the details. Team is working on this feature request and finalizing the details on how will this be launched. We are hoping to have something to share in near future (a quarter or so) if no major blockers. We will write back on this thread as we make progress or have meaningful update to share.

**Comment by zoyahav** [comment]
TFT now supports TFXIO input including its fast TFExampleDecoder, more information at https://github.com/tensorflow/transform/blob/master/docs/get_started.md#data-formats-and-schema.
