### ISSUE TITLE
"bad inputs" error very challenging to debug

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#118]
Are there any tips for how to properly debug a "[bad inputs](https://github.com/tensorflow/transform/blob/9aa8819a415fb7d0473323043d8d17f609a18cc7/tensorflow_transform/beam/impl.py#L396)" error? This seems to happen fairly frequently, especially when working with sparse tensors (I most commonly see it when working with sparse-to-dense conversions).

The problem is that this error just dumps a single row of data without any context for what caused the error. There is a [TF error log](https://github.com/tensorflow/transform/blob/9aa8819a415fb7d0473323043d8d17f609a18cc7/tensorflow_transform/beam/impl.py#L393-L395) that gets printed right before the exception is raised, which provides marginally more context, but it seems like I am only able to see it when using `DirectRunner`. When I run this with `DataflowRunner` the TF error is nowhere to be found in the logs.

What can be done to make "bad inputs" easier to debug?

**Comment by KesterTong** [comment]
We don't have specific fixes in mind for this issue, but debugability is a priority in the high level design as we move forward with TF.  For example, as we evolve the coders, we are trying to ensure that any data the coder produces will be valid for the preprocessing_fn.  And so any error with the data will happen in the coder, and result in a readable error.

**Comment by gowtham-kp** [comment]
@cyc Did that answer ypur question. Can I close the issue? Thanks!

**Comment by cyc** [comment]
Sure. There is not much actionable remaining aside from what @KesterTong mentioned.
