### ISSUE TITLE
SavedModel exported from TFT still contains references to TFT assets

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#120]
In order to reproduce this, you will need a dataset with some string features, and a TFT preprocessing_fn with `tft.compute_and_apply_vocabulary`. When you export the SavedModel as shown in [census_example.py](https://github.com/tensorflow/transform/blob/master/examples/census_example.py#L300-L307), the resulting SavedModel `${SAVED_MODEL_DIR}/saved_model.pb` will contain URL references to the `${TFT_DIR}/transform_fn/assets/${FEATURE_NAME}` file instead of the `${SAVED_MODEL_DIR}/assets/${FEATURE_NAME}` file. This seems to violate the stated design goal that SavedModels should be a hermetic representation of the resulting model.

In particular, this can cause problems if TFT and TF model training output to different GCS buckets and consumers of the resulting TF SavedModel have read permissions to only the TF model training bucket but not the TFT bucket. Or if there are different data retention policies for the two buckets and once the assets in the TFT bucket expire the SavedModel will no longer be initializable. It seems to me that once you export the SavedModel it should be self-contained and should no longer have any references to the TFT graph that helped produce it.

**Comment by cyc** [comment]
Also, since I am not super familiar with the design here, I am not sure whether this is actually working as intended or not. But if it is indeed a bug, it would be appreciated if you could suggest a workaround for the time being.

**Comment by KesterTong** [comment]
I think this is more a matter of TF internals.  Filenames get rewritten (and assets get copied) at various points in a SavedModel "lifecycle".  So just because the filename appears to refer to a file outside the SavedModel directly, this might actually get rewritten and end up reading from the SavedModel directory.

If you have evidence that the problems you describe are actually happening, please re-open the bug, but if this is just a theoretical concern I think it's safe to assume that the apparent non-hermeticity is just an artifact of TF internals.

**Comment by cyc** [comment]
@KesterTong sorry, I should have clarified, this is an actual production concern that I have, not just a theoretical concern. In order to work around this issue, I have had to stop using `tft.apply_vocabulary` entirely and only use TFT to compute the vocabulary, but leave the feature untransformed in TFT. Then I load the assets file into memory and include it as a `categorical_column_with_vocabulary_list`. This way the resulting SavedModel contains no references to the TFT SavedModel and is portable.

**Comment by KesterTong** [comment]
First, it's not clear we're talking about the same thing with the census example.  You referred to `${SAVED_MODEL_DIR}/saved_model.pb` but I'm not sure what that means.  Are you referring to the file (relative to the `--working_dir` argument) with path `exported_model_dir/<numbers>/saved_model.pb`.

When I run the census example, I see the above file, and it contains *relative* filenames (e.g. `education`).

**Comment by KesterTong** [comment]
Can you confirm you are running the latest version of the census_example code?

**Comment by cyc** [comment]
Sorry, I think I linked to the wrong example in my original post. I meant to reference [`sentiment_analysis`](https://github.com/tensorflow/transform/blob/master/examples/sentiment_example.py). Note that `census_example` uses `tft.vocabulary` and then `tf.feature_column.categorical_column_with_vocabulary_file` (meaning that TFT does not transform the categorical string features, rather the feature column does instead). However, in `sentiment_analysis` the function `tft.compute_and_apply_vocabulary` is used, meaning TFT stores the categorical string transformation in its `transform_fn`.

If you run `sentiment_analysis` and then you inspect the `saved_model.pb` in the workdir, you will see references to files like this: `/var/folders/6h/dgvmqj816g72301t0dsbzfs00000gp/T/tmpUEKJc6/tftransform_tmp/vocab_compute_and_apply_vocabulary_vocabulary`. I have not tried training a model with the transformed sentiment analysis data, but from my experience earlier the resulting saved model will also have the same reference to that file. Obviously, this is not ideal, it should be a relative file path to the assets directory.

**Comment by KesterTong** [comment]
Let me clarify one more time what I meant by "theoretical" vs "practical" concern.

What I should have said is: have you seen an error where serving fails because it is trying to read from a directory other than exported SavedModel?  Or do you *believe* that such an error would occur based on the content of the SavedModel?

I took a look at the SavedModel from the sentiment example and saw that while some references to the old absolute file paths remain, the "saved_model_assets" collection contains the relative filename as it should.

**Comment by KesterTong** [comment]
I have also update `sentiment_example_test.py` to delete the `transform_fn` dir and temp dir before testing serving the model, and those tests pass.  So the SavedModel exported by `sentiment_example.py` is hermetic

**Comment by KesterTong** [comment]
See https://github.com/tensorflow/transform/commit/91ef1172dabba3558b9f52a37b8bb5b234befbda

**Comment by rmothukuru** [comment]
@cyc ,
Can you please let us now if your issue is resolved. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by wsuchy** [comment]
When I use `tft.compute_and_apply_vocabulary` and save the function then the path to my vocabulary is hard coded in pb file like this: `/var/folders/h3/zt26x1d93hq49vff996w04pc0000gq/T/tmp4p0ho6g6/....`
