### ISSUE TITLE
TF Transform RuntimeError: AssertionError [while running 'AnalyzeAndTransformDataset/TransformDataset/Transform']

### ISSUE THREAD

**Issue by WillianFuks** [tensorflow/transform#122]
Asked this question on SO, will try to also start a thread here to see if we can find what's going on:

I'm working with the following code using tensorflow-transform:
```
import tensorflow as tf
import apache_beam as beam
import tensorflow_transform as tft
from tensorflow_transform.beam import impl as beam_impl
from tensorflow_transform.coders import example_proto_coder
from tensorflow_transform.tf_metadata import dataset_metadata
from tensorflow_transform.tf_metadata import dataset_schema
from tensorflow_transform.beam.tft_beam_io import transform_fn_io
import tempfile


import ast
import six
import apache_beam as beam
# Beam Pipelines must receive a set of config options to set how it should run.
from apache_beam.options.pipeline_options import PipelineOptions

assert six.PY2

options = {
    'runner': 'DirectRunner'
}

pipeline_options = PipelineOptions(**options)

RAW_DATA_SCHEMA = {
    'customer_id': dataset_schema.ColumnSchema(tf.string, [], dataset_schema.ListColumnRepresentation())
}
RAW_DATA_METADATA = dataset_metadata.DatasetMetadata(dataset_schema.Schema(RAW_DATA_SCHEMA))


def preprocess_fn(dictrow):
    return {
        'customer_id': tft.string_to_int(dictrow['customer_id'], vocab_filename='vocab_result')
    }

working_dir = tempfile.mkdtemp(dir='/tmp/')

with beam.Pipeline(options=pipeline_options) as pipeline:
    with beam_impl.Context(tempfile.mkdtemp()):
        raw_data = (
            pipeline
            | 'create' >> beam.Create([
                {'customer_id': ['customer_0']},
                {'customer_id': ['customer1', 'customer2']},
                {'customer_id': ['customer_0']}
            ])
        )

        raw_dataset = (raw_data, RAW_DATA_METADATA)
        transformed_dataset, transform_fn = (
            raw_dataset | beam_impl.AnalyzeAndTransformDataset(preprocess_fn))

        transformed_data, transformed_metadata = transformed_dataset

        OUTPUT_SCHEMA = {
            'customer_id': dataset_schema.ColumnSchema(tf.int64, [], dataset_schema.ListColumnRepresentation())
        }

        _ = transformed_data | 'writing' >> beam.io.tfrecordio.WriteToTFRecord(
            working_dir + '/tf', coder=example_proto_coder.ExampleProtoCoder(dataset_schema.Schema(OUTPUT_SCHEMA)))

        pipeline.run().wait_until_finish()
```

But it gives me the error:

> tftrec/local/lib/python2.7/site-packages/tensorflow_transform/beam/impl.pyc in process(self, batch, saved_model_dir) 438 # This should remain true throughout the lifetime of this DoFn, regardless 439 # of whether or not self._graph_state was cached. --> 440 assert self._graph_state.saved_model_dir == saved_model_dir 441 442 yield self._handle_batch(batch)
> 
> RuntimeError: AssertionError [while running 'AnalyzeAndTransformDataset/TransformDataset/Transform']

I wonder what could be wrong. I tried printing self._graph_state.saved_model_dir and indeed it does change but not sure why this happens.

Running tensorflow==1.13.1, tensorflow-transform==0.13.0, apache_beam[gcp]==2.11 on Python2

Testing for transform version 0.8 works (but still throws this error at times)

It seems to be an issue related to the final writing tfrecord process (when I remove it the error seems to go away)

**Comment by KesterTong** [comment]
I think that the problem is that `with beam.Pipeline(options=pipeline_options) as pipeline:` implicitly calls `pipeline.run()` at the end of the `with` block, but you also explicitly call `pipeline.run()`.

Calling `pipeline.run()` twice might result in unexpected behavior.

**Comment by rmothukuru** [comment]
@WillianFuks ,
Can you please try @KesterTong's suggestion and let us know if your issue is resolved. Thanks!

**Comment by WillianFuks** [comment]
Hi guys,

Sorry for the late reply. I tested here and it seems to be working :)! If the error throws again in the future I'll let you know.

**Comment by rmothukuru** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=122)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=122)
