### ISSUE TITLE
TF=GPU 2.0.0b TF Transform missing AUTOTUNE on import

### ISSUE THREAD

**Issue by Ryandry1st** [tensorflow/transform#123]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): POSIX
- TensorFlow version: 2.0.0b-gpu
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 
- GPU model and memory: Tesla T4

**Describe the problem**
Attempted to use TFX, specifically TF Transform, however when importing TF Transform it throws the error that AUTOTUNE is unknown.

`!pip install tensorflow_transform`
`import tensorflow_transform as tft`

**Any other info / logs**
AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'
For the full log see the attached file

[TF_Transform_Import_Error.txt](https://github.com/tensorflow/tensorflow/files/3302615/TF_Transform_Import_Error.txt)

**Comment by gowtham-kp** [comment]
Can you please run your code in [google colab](https://colab.sandbox.google.com/drive/) and see whether the error still persists. In Tensorflow 2.0 beta, 'contrib' module is deprecated but I see that in your error log, "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/data/__init__.py" contib module still exists. I doubt you might be running different version of Tensorflow. Please check the version of Tensorflow you are running. thanks!

**Comment by Ryandry1st** [comment]
I did check it again and it performs exactly the same, with the same error message. If TF2.0 is not supported then this is likely causing the import error. Would you prefer that I close the issue, as support is not currently available?

**Comment by gowtham-kp** [comment]
Yes @Ryandry1st we can close the issue for now. Infuture once the support is available we can add additional comments to open this issue..!

**Comment by r-or** [comment]
Hi,
I get the same issue when I try to use the tool _import_pb_to_tensorboard_ in python/tools.
Reproduction:
```
!pip3 install tensorflow-gpu==2.0.0-beta1
from tensorflow.python.tools import import_pb_to_tensorboard
```

`
Traceback (most recent call last):
  File "/tensorflow-2.0.0b1/python3.6/tensorflow/python/tools/import_pb_to_tensorboard.py", line 38, in <module>
    from tensorflow.contrib.tensorrt.ops.gen_trt_engine_op import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/__init__.py", line 38, in <module>
    from tensorflow.contrib import data
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/data/__init__.py", line 103, in <module>
    from tensorflow.contrib.data.python.ops.readers import CsvDataset
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/data/python/ops/readers.py", line 48, in <module>
    prefetch_buffer_size=optimization.AUTOTUNE,
AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'
`

**Comment by jasonrims** [comment]
Any luck with this issue? I am facing same issue with 'AUTOTUNE' attr..
