### ISSUE TITLE
Reading vocabulary file during AnalyzeAndTransformDataset

### ISSUE THREAD

**Issue by TimSmole** [tensorflow/transform#126]
I would like to read vocabulary file during [AnalyzeAndTransformDataset](https://www.tensorflow.org/tfx/transform/api_docs/python/tft_beam/AnalyzeAndTransformDataset). 

I found that [TFTransformOutput](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TFTransformOutput) provides such functionalities, however these methods are not available during [AnalyzeAndTransformDataset](https://www.tensorflow.org/tfx/transform/api_docs/python/tft_beam/AnalyzeAndTransformDataset) since [TFTransformOutput](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TFTransformOutput) searches for vocabulary files inside [TRANSFORM_FN_DIR](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TFTransformOutput#TRANSFORM_FN_DIR) which is not yet generated at that time. 

Another way I found is using same functions that apply_vocabulary is using - e.g. by using [tf.lookup.TextFileInitializer](https://www.tensorflow.org/api_docs/python/tf/lookup/TextFileInitializer) and [tf.lookup.StaticHashTable](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable), however this seems as a lot of duplicated and boilerplate code only to read the size of just created look-up table/vocabulary.

Are there any better ways to read vocabulary files?

Any advice will be highly appreciated! Thanks!

**Comment by KesterTong** [comment]
There is nothing simpler than the code in https://github.com/tensorflow/transform/blob/master/tensorflow_transform/mappers.py#L693 which I believe is what you are already doing.

**Comment by TimSmole** [comment]
@KesterTong thanks for reply.

Actually what I would like to do is to convert VarLenFeature (e.g. SparseTensor of string values) into multiple dummy features. In pandas this is as simple as call to [pd.to_dummies](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html). Since I could not find similar implementation in TFT my initial idea was to compute [vocabulary](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/vocabulary) to obtain mapping from string to integer values, apply [tf.one_hot ](https://www.tensorflow.org/api_docs/python/tf/one_hot) and [tf.math.reduce_sum](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) to obtain dummy values. Nevertheless I [tf.one_hot ](https://www.tensorflow.org/api_docs/python/tf/one_hot) requires the depth parameter - size of vocabulary ([StaticHashTable in this case](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable)). And even if I obtain the size of the table with [tf.contrib.lookup.index_table_from_file](https://www.tensorflow.org/api_docs/python/tf/contrib/lookup/index_table_from_file) (which will be removed in TF 2.0 I assume) I am still stuck at dynamically generating new features (dummy columns) for each value in vocabulary. 

To be honest I am not sure anymore if this is the correct approach. Should I convert features to dummy values with Apache Beam beforehand and only afterwards use TFT for things like feature scaling, imputation and so on?

Suggestions on better approach or general guidelines are very welcomed! Thanks!

**Comment by KesterTong** [comment]
TFT isn't designed to dynamically create features.  It is assumed that both the input and output features will be known in advance (before AnalyzeAndTransformDataset is called) and will not depend on the data itself.

Note that we do something which is logically equivalent in the [sentiment example](https://github.com/tensorflow/transform/blob/master/examples/sentiment_example.py).  In that example we create a multivalent, integer valued feature representing a bag of words, which we then use in an embedding (using the feature column API).

**Comment by gowtham-kp** [comment]
@TimSmole Did that answer your question. Can I close the issue?

**Comment by TimSmole** [comment]
@gowtham-kp Sorry for late response. I haven't had the time to try out [sentiment example](https://github.com/tensorflow/transform/blob/master/examples/sentiment_example.py). I am a bit surprised TFT will not support dynamic feature creation. But I guess this answers the question and we can close the issue for now. Thanks @KesterTong !

**Comment by JoshLipschultz** [comment]
Just to revisit this closed issue - I'm also in a position where I'd like to apply a `tf.one_hot(x, depth=table.size())` and some other step to the output of a `tft.compute_and_apply_vocabulary` transform, but am unable to. This would be an important improvement from my point of view. I've seen training speed improvements by doing this encoding beforehand.

The sentiment analysis isn't similar, since you pass in `VOCAB_SIZE` as a constant. I've been tinkering around with various `preprocessing_fn`s but have been unable to get this working. Is there a way to, for example, pass in a PValue computed in beam beforehand to the `preprocessing_fn`?

Thanks
