### ISSUE TITLE
Tag-set transform is not easily reusable for serving

### ISSUE THREAD

**Issue by cyrilou242** [tensorflow/transform#127]
Hello,

I am trying to serve a transform model on Google AI Platform.   
Unfortunately, when I check the tag-set with the cli utility, I see that a tensorflow transform model is saved with the tag `transform`. The AI Platform is expecting the tag `serve`.
	
	saved_model_cli show --dir out/transform/transform_fn
	transform

The tag `transform` seems to be a tag specific to tf transform that is not in the documentation of [tensorflow tags](https://www.tensorflow.org/api_docs/python/tf/saved_model/tag_constants), namely 'gpu', 'serve', 'tpu', and 'train'.

It's usage can be found here in the `write_saved_transform_from_session` function.
https://github.com/tensorflow/transform/blob/d3d4d1c7fa183866cb6ba5124be0b51d8b42af2d/tensorflow_transform/saved/saved_transform_io.py#L385

What is the reason for this `transform` tag ? 
Is reloading the model in a session and saving with the correct `serve` tag enough to have a working model, or will it break something ?

Would it be interesting to be able to pass the `serve` tag instead of the `transform` tag when saving in tensorflow transform ?

**Comment by KesterTong** [comment]
The graph that Transform produces was not designed to be served directly.  It is intended that the TFTransformOutput helper class is used to incorporate this graph into the model when constructing a model (e.g. using the Estimator API).  See our code samples.

**Comment by cyrilou242** [comment]
Thanks, sure, I understand the point but in my context I am not owning the model part. 

For anybody in the same context, I think the best solution is to reload the model in a Beam context.
(but this put some constraints on IO)

```
transform_fn = pipeline | tft_beam.ReadTransformFn(transform_dir)

transformed_data, _ = (
                (raw_data, transform_fn)
                | 'Transform' >> impl.TransformDataset()
        )
```
