### ISSUE TITLE
Is MeanAndVarCombiner a public API?

### ISSUE THREAD

**Issue by shoyer** [tensorflow/transform#130]
I'm interested in using the `tensorflow_transform.MeanAndVarCombiner` directly in my own Beam pipeline, without relying (yet) upon the rest of tf.Transform.

Is this API supported for external use?

I would have said yes, since it's exposed in the top level namespace in the latest release, but I noticed that it as replaced by `WeightedMeanAndVarCombiner` and is it's actually no longer available on master:
https://github.com/tensorflow/transform/commit/b6c3e02c0e86e091ab260f9c72cfe61917990fd8

Was this a mistake -- perhaps there should still be an alias `MeanAndVarCombiner = WeightedMeanAndVarCombiner` exposed? Or should I refrain from using either of these unless I'm willing to be broken? I It's a little hard to know what's a public API without API docs :).

**Comment by KesterTong** [comment]
Generally the source of truth for the public API is our API docs: https://www.tensorflow.org/tfx/api_docs, though in this case MeanAndVarCombiner was accidentally exposed as a public symbol and included in the API docs.  We have fixed this at HEAD.

We follow semver so there will be breaking changes between minor versions until we reach 1.0.  But these changes will be minimized and documented in the release notes.  Changes to non-public symbols will not be documented.

**Comment by shoyer** [comment]
OK, thanks, I'm not sure how I missed the API docs :).

To clarify -- it sounds like `WeightedMeanAndVarCombiner` is not intended to be a public API?

**Comment by KesterTong** [comment]
Yes `WeightedMeanAndVarCombiner` was not intended to be public, and will be removed from the public symbols (and API docs) in the next release.

**Comment by shoyer** [comment]
Thanks for the clarification!
