### ISSUE TITLE
Shouldn't categorical_column_with_vocabulary_file be wrapped with indicator_column in census_example.py?

### ISSUE THREAD

**Issue by Efaq** [tensorflow/transform#133]
I was working with census_example.py and noticed that the one_hot feature columns are being declared this way:

```
# Wrap categorical columns.
  one_hot_columns = [
      tf.feature_column.categorical_column_with_vocabulary_file(
          key=key,
          vocabulary_file=tf_transform_output.vocabulary_file_by_name(
              vocab_filename=key))
      for key in CATEGORICAL_FEATURE_KEYS]
```

As far as I could understand, the categorical_column_with_vocabulary_file feature column is mapping strings to integers, but no one-hot encoding is being performed. The encoding would be achieved using tf.feature_column.indicator_column around the resulting categorical column.

Thus, I would write it this way:

```
# Wrap categorical columns.
  one_hot_columns = [
tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_file(
          key=key,
          vocabulary_file=tf_transform_output.vocabulary_file_by_name(
              vocab_filename=key)))
      for key in CATEGORICAL_FEATURE_KEYS]
```
Am I correct or have I misunderstood the usage of these tf.feature_column.*?

Thanks!

**Comment by gowtham-kp** [comment]
@Efaq As mentioned [here,](https://www.tensorflow.org/api_docs/python/tf/feature_column/indicator_column) You should be able to use the output of 'categorical_column_with_*' as an argument to  'tf.feature_column.indicator_column'. This should work.

**Comment by Efaq** [comment]
Hi @gowtham-kp thank you for the answer! Yes, I have been using it like that (with indicator_column) and I have seen the referred docs, so I agree that it works.

But my question is if the way it is being done in census_example.py (WITHOUT indicator_column) is correct. It does work, in the sense that it doesn't crash, but you are in fact not doing a one-hot encoding of the feature. You are instead mapping the categorical feature values to integers. So instead of "a", "b" and "c", the model will receive "0", "1" and "2" for example. A one-hot encoding would instead create three new columns and use zeros and ones to indicate the feature value.

**Comment by rmothukuru** [comment]
@Efaq ,
As per [this link](https://www.tensorflow.org/api_docs/python/tf/feature_column/indicator_column), `tf.feature_column.indicator_column` Represents `multi-hot` representation of given categorical column. As per [this link](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file) and in the "Categorical Vocabulary Column" of this [Google Blog](https://developers.googleblog.com/2017/11/introducing-tensorflow-feature-columns.html), `tf.feature_column.categorical_column_with_vocabulary_file`, performs represents `One-Hot` representation of given `Categorical Column`.

If you differ from my explanation, can you please elaborate your point with example data and printing the respective values. Thanks!

**Comment by Efaq** [comment]
Hi @rmothukuru, thanks!

Your first reference to Categorical Vocabulary Column, namely [this](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file), didn't help. There was no mention to one-hot encoding as far as I could find.

In the google blog document you referred to ([this](https://developers.googleblog.com/2017/11/introducing-tensorflow-feature-columns.html)), **they seem to confirm what I said**. Please read it through and note the part beginning in this paragraph:

> Let's look at an example comparing indicator and embedding columns. Suppose our input examples consists of different words from a limited palette of only 81 words. Further suppose that the data set provides the following input words in 4 separate examples:

They explain, together with an illustration, that `categorical_column_with_hash_bucket`, `categorical_column_with_vocabulary_list` and `categorical_column_with_vocabulary_file` map a categorical feature to numeric value:

![image](https://user-images.githubusercontent.com/42271354/62375272-326b3f80-b53e-11e9-8dd9-1849d3f06b8b.png)

Then, after that, you can use `indicator_column` to do the one-hot encoding. I quote:

> When an example is processed, one of the categorical_column_with... functions maps the example string to a numerical categorical value. For example, a **function maps "spoon" to [32]**. (The 32 comes from our imagination—the actual values depend on the mapping function.) You may then represent these numerical categorical values in either of the following two ways:
> 
> **As an indicator column. A function converts each numeric categorical value into an 81-element vector (because our palette consists of 81 words), placing a 1 in the index of the categorical value (0, 32, 79, 80) and a 0 in all the other positions.**

**So why does the census example work without the indicator column**?

What happens is that, in the case of linear models (this is the case of the census example), you don't need to use the indicator column (still not sure why, but there are references confirming this. Please see in the end). But if you change the model to a NN, **you will have an error**. Test the following:

1)Run the census example as it is (using `tf.estimator.LinearClassifier`). Everything works fine.
2)Replace the linear model with a simple neural net. Namely, replace the following code snippet:
```
  estimator = tf.estimator.LinearClassifier(
      feature_columns=get_feature_columns(tf_transform_output),
      config=run_config)
```
with the following:
```
  estimator = tf.estimator.DNNClassifier(
      hidden_units=[30,20],
      feature_columns=get_feature_columns(tf_transform_output),
      config = run_config
  )
```
I get a stack trace ending in:
```
ValueError: Items of feature_columns must be a DenseColumn. You can wrap a categorical column with an embedding_column or indicator_column. Given: VocabularyFileCategoricalColumn(key='education', vocabulary_file='.\\Data\\Census\\Output\\transform_fn\\assets\\education', vocabulary_size=16, num_oov_buckets=0, dtype=tf.string, default_value=-1)
```

If I use `tf.feature_column.indicator_column` to wrap `tf.feature_column.categorical_column_with_vocabulary_file` as I mentioned in my first post, the code works with both linear models and NNs.

**Regarding the example, what I think could be done:**

Since the census example is a tutorial example, and first contact of many people with tensorflow transform, I think it would be appropriate to either add the `tf.feature_column.indicator_column` wraping `tf.feature_column.categorical_column_with_vocabulary_file`, so the code works with models other than `tf.estimator.LinearClassifier`, or to add a comment mentioning the issue discussed here. Otherwise, people wanting to try different models will face the error above.

**About the references:**

Some references mentioning that linear models can skip the indicator column.

[Ref1](https://www.tensorflow.org/api_docs/python/tf/feature_column/indicator_column):

> For DNN model, indicator_column can be used to wrap any categorical_column_* (e.g., to feed to DNN). Consider to Use embedding_column if the number of buckets/unique(values) are large.
> 
> For Wide (aka linear) model, indicator_column is the internal representation for categorical column when passing categorical column directly (as any element in feature_columns) to linear_model. See linear_model for details.

[Ref2](https://www.tensorflow.org/api_docs/python/tf/feature_column/linear_model):

> Note on supported columns: linear_model treats categorical columns as indicator_columns. To be specific, assume the input as SparseTensor looks like:

> linear_model assigns weights for the presence of "a", "b", "c' implicitly, just like indicator_column, while input_layer explicitly requires wrapping each of categorical columns with an embedding_column or an indicator_column.

[Ref3](https://www.tensorflow.org/tutorials/estimators/linear):

> The input_layer function we're using is designed for DNN models and expects dense inputs. To demonstrate the categorical column we must wrap it in a tf.feature_column.indicator_column to create the dense one-hot output (Linear Estimators can often skip this dense-step).

Ref4 - A small code example showing the error when not using indicator_column:

```
import tensorflow as tf

colors_column = tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list(
    key='color',
    vocabulary_list=["Green", "Red", "Blue", "Yellow"]
))

#colors_column = tf.feature_column.categorical_column_with_vocabulary_list(
#    key='color',
#    vocabulary_list=["Green", "Red", "Blue", "Yellow"]
#)

input_layer = tf.feature_column.input_layer(
    features={'color': tf.constant(value="Red", dtype=tf.string, shape=(1,))},
    feature_columns=[colors_column])


with tf.Session() as sess:
    sess.run(tf.initialize_all_tables())
    print(sess.run(input_layer))


```

Please let me know if you don't agree with the code examples, references or with my suggestion for the change.

**Comment by rmothukuru** [comment]
@Efaq ,
Thank you for the detailed explanation. We will revert shortly.

**Comment by michaelwunder** [comment]
We made the suggested change [here](https://github.com/tensorflow/transform/commit/ad5c606dbe85da7ed513d4556e5e08624c744cff#diff-96bb52d663d13fb07f8d90d39ac4572e). Seems like we want to aim for consistency across models.
