### ISSUE TITLE
No variables to save error when applying function with checkpoint

### ISSUE THREAD

**Issue by jasonquekavalon** [tensorflow/transform#134]
Hi,

My tensorflow version is 1.13.2, tft version is 0.13.0, apache-beam version is 2.13.0.

I am receiving a No variables to save exception when running apply_function_with_checkpoint and supplying a path to the inceptionv3 checkpoints.

    def _image_to_vec(image_str_tensor):

        def _decode_and_resize(image_str_tensor):
            """Decodes jpeg string, resizes it and returns a uint8 tensor."""

            # These constants are set by Inception v3's expectations.
            height = 299
            width = 299
            channels = 3

            image = tf.read_file(image_str_tensor)
            image = tf.image.decode_jpeg(image, channels=channels)
            image = tf.expand_dims(image, 0)
            image = tf.image.resize_bilinear(image, [height, width],
                                            align_corners=False)
            image = tf.squeeze(image, squeeze_dims=[0])
            image = tf.cast(image, dtype=tf.uint8)
            return image

            image = tf.map_fn(_decode_and_resize, image_str_tensor,
                            back_prop=False, dtype=tf.uint8)

            image = tf.image.convert_image_dtype(image, dtype=tf.float32)
            image = tf.subtract(image, 0.5)
            inception_input = tf.multiply(image, 2.0)

            # Build Inception layers, which expect a tensor of type float from [-1, 1)
            # and shape [batch_size, height, width, channels].
            with tf.contrib.slim.arg_scope(inception_v3_arg_scope()):
                _, end_points = inception_v3(inception_input, is_training=False)
            
            embeddings = end_points['PreLogits']
            inception_embeddings = tf.squeeze(embeddings, [1, 2], name='SpatialSqueeze')
            return inception_embeddings

    def make_tft_input_metadata():

        return dataset_metadata.DatasetMetadata(
            dataset_schema.from_feature_spec({
                'image': tf.FixedLenFeature([], tf.string),
                'label': tf.FixedLenFeature([], tf.string)
            })
        )

    def preprocessing_fn(inputs):
        """TFT preprocessing function.
        Args:
        inputs: dictionary of input `tensorflow_transform.Column`.
        Returns:
        A dictionary of `tensorflow_transform.Column` representing the transformed
            columns.
        """

        features_dict = {}

        features_dict['image'] = tft.apply_function_with_checkpoint(
                _image_to_vec,
                [inputs['image']],
                INCEPTION_V3_CHECKPOINT,
                exclude=INCEPTION_EXCLUDED_VARIABLES)

        features_dict['label'] = tft.string_to_int(
            inputs['label'],
            vocab_filename='vocab_label')

        return features_dict

    def run_transform(output_dir, train_data_file, eval_data_file,
                    project, mode):
        tft_input_metadata = make_tft_input_metadata()
        temp_dir = os.path.join(output_dir, 'tmp')

        if mode == 'local':
            pipeline_options = None
            runner = 'DirectRunner'
        elif mode == 'cloud':
            options = {
            'job_name': 'pipeline-tft-' + datetime.datetime.now().strftime('%y%m%d-%H%M%S'),
            'temp_location': temp_dir,
            'project': project
            }
            pipeline_options = beam.pipeline.PipelineOptions(flags=[], **options)
            runner = 'DataFlowRunner'
        else:
            raise ValueError("Invalid mode %s." % mode)

        with beam.Pipeline(runner, options=pipeline_options) as p:
            with beam_impl.Context(temp_dir=temp_dir):
                names = ['image', 'label']
                converter = CsvCoder(names, tft_input_metadata.schema)
                train_data = (
                    p
                    | 'ReadTrainData' >> textio.ReadFromText(train_data_file)
                    | 'DecodeTrainData' >> beam.Map(converter.decode))

                train_dataset = (train_data, tft_input_metadata)
                transformed_dataset, transform_fn = (
                    train_dataset | beam_impl.AnalyzeAndTransformDataset(preprocessing_fn))
                transformed_data, transformed_metadata = transformed_dataset

The exception occurrs at AnalyzeAndTransformDataset.

Here is the stack trace

```
File "src/preprocess.py", line 131, in preprocessing_fn
    exclude=INCEPTION_EXCLUDED_VARIABLES)
  File "/Users/jason.quek/virtualenvs/comex-preprocess-9xyR313c/lib/python3.5/site-packages/tensorflow_transform/pretrained_models.py", line 201, in apply_function_with_checkpoint
    saver = tf.train.Saver(vars_to_restore)
  File "/Users/jason.quek/virtualenvs/comex-preprocess-9xyR313c/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Users/jason.quek/virtualenvs/comex-preprocess-9xyR313c/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/jason.quek/virtualenvs/comex-preprocess-9xyR313c/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 869, in _build
    raise ValueError("No variables to save")
```

Tracing the code, it looks like tf.contrib.slim.get_variables_to_restore is used to get the variables from an empty Graph, but I'm not certain. I adapted the code samples from the flower kubeflow pipeline, but it was on tf 1.6.0 and tft 0.6.0, so I wanted to move to the latest versions. Might you have any idea on the reason behind this ?

**Comment by gowtham-kp** [comment]
@jasonquekavalon As mentioned [here](https://stackoverflow.com/questions/38626435/tensorflow-valueerror-no-variables-to-save-from) tf.train.Saver must be created after the variables that you want to restore (or save). Please also note that this is not a Tensorflow/Transform issue. You can get faster response on [Tensorflow/Tensorflow](https://github.com/tensorflow/tensorflow) as [tf.contrib.slim](https://www.tensorflow.org/api_docs/python/tf/contrib/slim) is a Tensorflow module.

**Comment by jasonquekavalon** [comment]
Hi @gowtham-kp ,
If you look at the code in tensorflow-transform, it tries to retrieve variables in apply_function_with_checkpoint.

But it is using a default graph with no variables initialized there, which is why I created the bug here in tensorflow-transform

´´´
def apply_function_with_checkpoint(fn, inputs, checkpoint, include=None,
                                   exclude=None):
  """Applies a tensor-in-tensor-out function with variables to some `Tensor`s.

  Variable values are loaded from the given checkpoint path. Note that the
  input_tensor_func, together with the checkpoint, will be converted to an
  all-constants graph, so ops requiring graph collections, such as table lookup
  (which requires a table init op being added to TABLE_INITIALIZERS collection),
  are not supported.

  Args:
    fn: A tensor-in-tensor-out function that may contain variables.
    inputs: A list of `Tensor`s to apply `fn` to.
    checkpoint: The checkpoint path to load variables from.
    include: An optional list/tuple of scope strings for filtering which
        variables from the VARIABLES collection to include. If None, all
        variables will be included.
    exclude: An optional list/tuple of scope strings for filtering which
        variables from the VARIABLES collection to exclude. If None, no
        variables will be excluded.

  Returns:
    A `Tensor` or list of `Tensor`s representing the application of `fn`.

  Raises:
    ValueError: if the input tensor-in-tensor-out function adds to
        TABLE_INITIALIZERS collections.
  """
  loaded_graph = tf.Graph()
  with loaded_graph.as_default():
    input_placeholders = [
        tf.placeholder(dtype=tensor.dtype, shape=tensor.shape,
                       name=tensor.op.name)
        for tensor in inputs]
    output = fn(*input_placeholders)
    if isinstance(output, tf.Tensor):
      output_tensors = [output]
      output_single_tensor = True
    else:
      output_tensors = output
      output_single_tensor = False

    # TODO(qimingj/kestert): Copy table initializers to the composed graph.
    if tf.get_collection(tf.GraphKeys.TABLE_INITIALIZERS):
      raise ValueError('Models with table init ops are not supported.')

    vars_to_restore = tf.contrib.slim.get_variables_to_restore(
        include=include, exclude=exclude)
    saver = tf.train.Saver(vars_to_restore)
