### ISSUE TITLE
Schema and statistics in Transform TFX Pipeline Component

### ISSUE THREAD

**Issue by wsuchy** [tensorflow/transform#136]
The main entry point in Transform component (`preprocessing_fn`) should also provide computed Stats and Schema next to the inputs. In some scenarios users might want to benefit from the statistics e.g. to eliminate unnecessary features.
(also posted here: https://github.com/tensorflow/tfx/issues/629, it looks like the changes might be needed in both repos)

**Comment by zoyahav** [comment]
I don't think this will require changes to this library, let's discuss on https://github.com/tensorflow/tfx/issues/629.
Closing this for now.
