### ISSUE TITLE
Support for TF 2.0

### ISSUE THREAD

**Issue by maxzoech** [tensorflow/transform#141]
What's the status on support for TensorFlow 2.0 and is there a workaround in the meantime?

**Comment by gowthamkpr** [comment]
@maxzoech Cannot promise any concrete deadline for this. We are currently working on integrating TFT with TF2.0. It might take some time.

**Comment by michaelwunder** [comment]
As of the upcoming 0.15 release (see https://github.com/tensorflow/transform/blob/master/RELEASE.md), TF.Transform will offer experimental support for TF 2.0 in "safety" mode. In particular, programs using 1.X APIs, such as through tensorflow.compat.v1, are expected to work as intended. There may exist new functionality specific to TF 2.0 that is not fully supported right away, but over time, TFT will cover those use cases as well.
