### ISSUE TITLE
tft.compute_sample_weight()?

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/transform#145]
Sample or class weighting for imbalanced classification tasks requires a full pass over the training labels. It's a "temporary" transformation that will be thrown out after training, but would it make sense to implement this in tft?

Could I accomplish this with `sample_weights = tft.size(labels) / (n_classes * tf.unique_with_counts(labels)[2])`?

**Comment by rmothukuru** [comment]
@JakeTheWise,
Could you please elaborate your question.

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow Transform version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

**Comment by JakeTheWise** [comment]
I don't think my question relates to those things. I was just hoping to have a discussing about if it would be appropriate to implement a sample weight computation in tft.

**Comment by zoyahav** [comment]
I believe @michaelwunder is currently working on functionality that should help with this and will make into the next release of tf.Transform.

But yes, I think it makes sense to implement with tft since it requires full passes over the data, and would probably look similar to the snippet above.
A missing piece is the unique_with_counts operation that also does a full pass over the data which is what Michael will likely be adding.

**Comment by michaelwunder** [comment]
That's right, as of the next release, there will be functionality to achieve this task. 
The best bet would probably be to pass your labels into tft.histogram with categorical=True which will return the counts along with the corresponding labels. Then you can derive the weights from those counts to pass into the trainer.

There is also a mapper that will return the probability of each sample's label (or interval if continuous): tft.estimated_probability_density. 

See [this update.](https://github.com/tensorflow/transform/commit/7fccd88876c56496d252b713cd315f006c248084)

**Comment by JakeTheWise** [comment]
I've successfully implemented this as:
```python
def balanced_sample_weight(t: tf.Tensor) -> tf.Tensor:
    vocab, counts = tft.count_per_key(t)
    n_samples = tft.size(t)
    n_classes = tf.shape(vocab)[0]
    class_weights = tf.math.divide(n_samples, tf.math.multiply(tf.cast(n_classes, tf.int64), counts)) # n_samples / (n_classes * np.bincount(y))
    table = tf.lookup.StaticHashTable(tf.lookup.KeyValueTensorInitializer(keys=vocab, values=tf.cast(class_weights, tf.float32)), default_value=0)
    return table.lookup(t)
```

**Comment by michaelwunder** [comment]
Great that you were able to make use of these new methods for a novel use case we hadn't considered.
