### ISSUE TITLE
tft.tfidf does not work with tensorflow v2.0

### ISSUE THREAD

**Issue by wolfiex** [tensorflow/transform#148]
```
   2626   if context.executing_eagerly():
-> 2627     raise RuntimeError("tf.placeholder() is not compatible with "
   2628                        "eager execution.")
   2629 

RuntimeError: tf.placeholder() is not compatible with eager execution.
```
When using eager evaluation, but asking for a feed value placeholder without : 
`InvalidArgumentError: You must feed value for placeholder tensor 'tfidf/sum/Placeholder' with dtype double and shape `

**Comment by zoyahav** [comment]
Please share your code here or explain more about how you're using it.
tft.tfidf() should work with TF 2.0 similarly to other mappers that use an analyzer when running in the context of a tft.AnalyzeDataset (or AnalyzeAndTransformDataset).

**Comment by rmothukuru** [comment]
@wolfiex,
Can you please respond to @zoyahav's comment. Thanks!

**Comment by wolfiex** [comment]
Code as per the [documentation](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/tfidf), run in TensorFlow v2:
```
import tensorflow as tf
import tensorflow_transform as tft    

data = tf.SparseTensor(indices=[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [1, 0], [1, 1], [1, 2]], values=[1, 2, 0, 0, 0, 3, 3, 0],dense_shape=(8,2)) 

res = tft.tfidf(
    data,
    4,
    smooth=True,
    name=None
)
```

Error failing at 
...
>  /Users/dna/miniconda2/lib/python2.7/site-packages/tensorflow_core/python/ops/array_ops.pyc in placeholder(dtype, shape, name)
>    2625   """
>    2626   if context.executing_eagerly():
> -> 2627     raise RuntimeError("tf.placeholder() is not compatible with "
>    2628                        "eager execution.")
>    2629 
> 
> RuntimeError: tf.placeholder() is not compatible with eager execution.
>

**Comment by zoyahav** [comment]
As I mentioned previously, calls to tft mappers and analyzers must happen in the context of a preprocessing_fn passed to tft.AnalyzeDataset (or AnalyzeAndTransformDataset).

The reason is that these operations require full passes over your data, and tf.transform uses beam to achieve that.

Please take a look at our tutorials: https://www.tensorflow.org/tfx/tutorials/transform/simple

**Comment by zoyahav** [comment]
If we translate your snippet @wolfiex to tf.transform's simple example as linked above we'll get this which ran successfully for me:
```
import pprint
import tempfile

import tensorflow as tf
import tensorflow_transform as tft
import tensorflow_transform.beam.impl as tft_beam
from tensorflow_transform.tf_metadata import dataset_metadata
from tensorflow_transform.tf_metadata import dataset_schema
tf.logging.set_verbosity(tf.logging.ERROR)

raw_data = [
      {'x': [1, 2, 0, 0, 0]},
      {'x': [3, 3, 0]},
  ]

raw_data_metadata = dataset_metadata.DatasetMetadata(
    dataset_schema.from_feature_spec({
        'x': tf.VarLenFeature(tf.float32),
    }))

def preprocessing_fn(inputs):
    index, weight = tft.tfidf(inputs['x'], 4, smooth=True, name=None)
    return {
        'index': index,
        'weight': weight, 
    }
with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
  transformed_dataset, transform_fn = (
      (raw_data, raw_data_metadata) | tft_beam.AnalyzeAndTransformDataset(
          preprocessing_fn))

transformed_data, transformed_metadata = transformed_dataset

print('\nRaw data:\n{}\n'.format(pprint.pformat(raw_data)))
print('Transformed data:\n{}'.format(pprint.pformat(transformed_data)))
```

> Raw data:
> [{'x': [1, 2, 0, 0, 0]}, {'x': [3, 3, 0]}]
> 
> Transformed data:
> [{'index': array([0, 1, 2]),
>   'weight': array([0.6       , 0.28109303, 0.28109303], dtype=float32)},
>  {'index': array([0, 3]),
>   'weight': array([0.33333334, 0.9369768 ], dtype=float32)}]

**Comment by wolfiex** [comment]
Thanks a lot for the working example @zoyahav ! 

It may be worth adding a note in the documentation (https://www.tensorflow.org/tfx/transform/api_docs/python/tft/tfidf)
such that other people (such as myself) are aware that this is how the function is intended to be used.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved. Thanks!
