### ISSUE TITLE
Can not export the transform graph from tf.Transform together with model definition using keras in TensorFlow 2.0.

### ISSUE THREAD

**Issue by brightcoder01** [tensorflow/transform#150]
**We cannot export the transform graph from tf.Transform and the graph from Keras Model together into a single SavedModel.**

**Background**
Let's focus on these three stages in the end-to-end machine learning lifecycle of TFX:  
`Transform stage`: [tf.Transform](https://github.com/tensorflow/transform) component transforms the raw data into the data used to train a machine learning model. It also exports the transform logic in the SavedModel format. We name it `saved_model_trans`.  
`Training stage`: TensorFlow uses the preprocessed data to train a model. After completing the training job, it exports the model graph together with the transform graph (from `saved_model_trans`) as one SavedModel. We name it `saved_model_final`.  
`Serving stage`: TensorFlow Serving can load `saved_model_final` to provide inference service. The schemas of the inference request and the raw data of the transform stage are exactly the same.  

**Current state**: how to export transform graph and model graph together to a SavedModel?  
√ Estimator (Work Well):  
From [tf.transform official tutorial](https://github.com/tensorflow/transform/blob/cf517f1a8765e6552d09cee65efea80e26c05f5e/examples/census_example.py#L380-L382), at the stage of exporting model, it will call [estimator.export_saved_model(exported_model_dir, serving_input_fn)](https://github.com/tensorflow/estimator/blob/b22a912de2693322622d6f50e3a19e98fecac441/tensorflow_estimator/python/estimator/estimator.py#L661) to complete the model exporting work. Inside its implementation, it calls serving_input_fn to load the transform graph from SavedModel at first, and then calls estimator's model_fn to generate the model graph, combines these two graph into one graph and finally exports it into one SavedModel. Please check the [code snippet](https://github.com/tensorflow/estimator/blob/43921b4552d1c30acc31d3b5989112cb397383e0/tensorflow_estimator/python/estimator/estimator.py#L926-L937).  

× Keras (Can not):  
For TF2.0, we define a model using keras and exports it by calling [tf.saved.saved_model](https://www.tensorflow.org/api_docs/python/tf/saved_model/save). This SavedModel only contains the model definition including feature columns and NN structure. `tf.saved.saved_model` api doesn't have the parameter `serving_input_fn` just like estimator and **it lacks the flexibility to combine transform graph and model graph together for inference. It will break the integration between tf.Transform and TensorFlow 2.0.**

**We want to improve `tf.saved.saved_model` api in Keras to support this function. So that TensorFlow 2.0 can work well with tf.Transform.**

**Comment by brightcoder01** [comment]
Hi, @zoyahav @rmothukuru , could you please share more information about this bug?

**Comment by JakeTheWise** [comment]
As a hack, I implemented a custom Keras layer that applies the tf-transform function (`saved_model_trans`) on my raw inputs. This ensures the preprocessing function is transmitted to the `saved_model_final` for serving. But it's very hacky and also doesn't allow preprocessing transformations on the raw targets (ie mapping strings to integers for classification tasks). Can we expect that tf-transform will support keras models?

**Comment by mrcolo** [comment]
Any progress on this issue?

**Comment by zoyahav** [comment]
Yes, tf.transform currently supports Keras, though we're actively working on improving this support.
There's currently the TFT layer which should be used when using Keras:
https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TFTransformOutput#transform_features_layer

Example usage: https://github.com/tensorflow/transform/blob/master/examples/census_example_v2.py#L344-L356
Note that the layer should be saved to the model as an attribute for resource tracking purposes.

**Comment by mrcolo** [comment]
Thanks, super helpful!

**Comment by rmothukuru** [comment]
@brightcoder01,
Can you please let us know if [this comment](https://github.com/tensorflow/transform/issues/150#issuecomment-694769276) has resolved your issue? Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
