### ISSUE TITLE
Unable to impute missing values with the mean using tf.Transform

### ISSUE THREAD

**Issue by thisisandreeeee** [tensorflow/transform#152]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-4.14.106+-x86_64-with-debian-buster-sid
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.6

**Describe the current behavior**
I am trying to impute the missing values in a tensor with the sample mean. As the size of my dataset is potentially quite large and the calculation of means require a full pass of the dataset, I am using tf.Transform to perform this computation.

As there is no native support for imputation on tf.Transform, I am implementing this by creating a `SparseTensor`, and specifying a default_value when converting to a dense tensor (as suggested by @KesterTong in https://github.com/tensorflow/transform/issues/78#issuecomment-427919062).

However, this does not seem to be successful as the output tensor still contains `nan`.

**Describe the expected behavior**
I expect the missing values in the output tensor to be replaced by the mean of the non-null values.

**Code to reproduce the issue**
```python
import tempfile
from glob import glob

import apache_beam as beam
import pandas as pd
import tensorflow as tf
import tensorflow_transform as tft
import tensorflow_transform.beam as tft_beam
from tensorflow_transform.tf_metadata import dataset_metadata, schema_utils

assert tf.__version__ == "2.0.0" and tft.__version__ == "0.15.0" and beam.__version__ == "2.16.0"

def create_raw_data(output_file):
    df = pd.DataFrame({"age": [35.2, 17.3, None, 25.0]})
    with tf.io.TFRecordWriter(output_file) as writer:
        for _, row in df.iterrows():
            features = tf.train.Features(
                feature={"age": tf.train.Feature(float_list=tf.train.FloatList(value=[row]))}
            )
            example_proto = tf.train.Example(features=features)
            writer.write(example_proto.SerializeToString())

            
def run_tftransform(input_file, output_file):
    def preprocessing_fn(inputs):
        def _impute(tensor, replacement):
            sparse = tf.sparse.SparseTensor(
                tensor.indices, tensor.values, [tensor.dense_shape[0], 1]
            )
            dense = tf.sparse.to_dense(sp_input=sparse, default_value=replacement)
            dense = tf.squeeze(dense, axis=1)
            return dense

        outputs = inputs.copy()
        mean_age = tft.mean(outputs["age"])
        outputs["age"] = _impute(outputs["age"], mean_age)  # mean is 25.833333333
        return outputs

    RAW_DATA_FEATURE_SPEC = {"age": tf.io.VarLenFeature(tf.float32)}
    RAW_DATA_METADATA = dataset_metadata.DatasetMetadata(
        schema_utils.schema_from_feature_spec(RAW_DATA_FEATURE_SPEC)
    )

    with beam.Pipeline() as pipeline:
        with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
            raw_data_coder = tft.coders.ExampleProtoCoder(RAW_DATA_METADATA.schema)
            raw_train_data = (
                pipeline | beam.io.ReadFromTFRecord(input_file, coder=raw_data_coder)
            )
            (transformed_train_data, transformed_metadata), transform_fn = (
                (raw_train_data, RAW_DATA_METADATA)| tft_beam.AnalyzeAndTransformDataset(preprocessing_fn)
            )
            transformed_data_coder = tft.coders.ExampleProtoCoder(transformed_metadata.schema)
            _ = (
                transformed_train_data| beam.io.WriteToTFRecord(
                    output_file, coder=transformed_data_coder
                )
            )
            
            
if __name__ == "__main__":
    create_raw_data("raw_data.tfrecord")
    run_tftransform("raw_data.tfrecord", "transformed_data.tfrecord")

    TRANSFORMED_FEATURE_SPEC = {"age": tf.io.FixedLenFeature([], tf.float32)}
    raw_dataset = tf.data.TFRecordDataset(filenames=glob("transformed_data.tfrecord*"))
    parsed_dataset = raw_dataset.map(lambda x: tf.io.parse_single_example(x, TRANSFORMED_FEATURE_SPEC)).batch(4)

    print(next(iter(parsed_dataset.take(1))))
```

Expected output:
```python
{'age': <tf.Tensor: id=533, shape=(4,), dtype=float32, numpy=array([35.2, 17.3,  25.8333, 25. ], dtype=float32)>}
```
Actual (incorrect) output which still contains `nan` values:
```python
{'age': <tf.Tensor: id=533, shape=(4,), dtype=float32, numpy=array([35.2, 17.3,  nan, 25. ], dtype=float32)>}
```

**Comment by zoyahav** [comment]
In this snippet, the missing value appears as NaN instead of a zero-length tensor due to how DataFrame treats Nones, and so the feature value isn't really missing in this case.
The following should work with your existing preprocessing_fn:

```
def create_raw_data(output_file):
    df = pd.DataFrame({"age": [35.2, 17.3, None, 25.0]})
    with tf.io.TFRecordWriter(output_file) as writer:
        for _, row in df.iterrows():
            if all(row.isna()):
              features = tf.train.Features(
                  feature={"age": tf.train.Feature(float_list=tf.train.FloatList())}
              )
            else:
              features = tf.train.Features(
                  feature={"age": tf.train.Feature(float_list=tf.train.FloatList(value=[row]))}
              )
            example_proto = tf.train.Example(features=features)
            print(example_proto)
            writer.write(example_proto.SerializeToString())
```

Note that if a feature is all NaN, it will be added to the tf.Example as an empty list:
`tf.train.Feature(float_list=tf.train.FloatList())`

Or as an alternative, in the preprocessing_fn, you could use tf.where to replace NaNs with the replacement value and keep create_raw_data as is.

**Comment by thisisandreeeee** [comment]
I would prefer to handle this in the `preprocessing_fn` instead since the upstream data could change. Are you suggesting the following implementation of impute?
```python
def _impute(tensor, value):
    replacement = tf.constant(value, shape=tensor.dense_shape)
    return tf.where(tf.math.is_nan(tensor), replacement, tensor)
```
This returns the following error:
```
NotImplementedError: Cannot convert a symbolic Tensor (inputs/inputs/age/shape_copy:0) to a numpy array.
```
I suspect this happens when `value` is the result of the `tft.mean(x)` call. 

I'm trying to impute mean values using tf.Transform, any suggestions or alternate ways to do so?

**Comment by zoyahav** [comment]
I believe that the issue you're facing now is with passing tensor.dense_shape to tf.constant.

The following should work (copied in part from the previous snippet):

```
def _impute(tensor, value):
  tensor = tf.sparse.SparseTensor(
      tensor.indices, tensor.values, [tensor.dense_shape[0], 1]
  )
  dense = tf.sparse.to_dense(sp_input=tensor, default_value=value)
  return tf.where(tf.math.is_nan(dense), value, dense)
```

This way you are handling both actually missing values, and NaN values.

**Comment by thisisandreeeee** [comment]
Thanks @zoyahav, the code runs now but the imputed value looks to be incorrect. 
```python
{'age': <tf.Tensor: id=1798, shape=(4,), dtype=float32, numpy=array([35.2 , 17.3 , 15.05, 25.  ], dtype=float32)>}
```
It seems that the mean is calculated to be 15.05, when it should be 25.83. This seems pretty odd.

**Comment by zoyahav** [comment]
Unfortunately it's a known issue that NaNs can produce unexpected results for some analyzers, luckily we can easily workaround it in your case.

Note that here we're using only `outputs["age"].values` since tft.mean is called with reduce_instance_dims=True, otherwise we would also have to take the indices under consideration.

The following should result in the right value:

```
  age_values = outputs["age"].values
  finite_age_indices = tf.math.is_finite(age_values)
  finite_age_values = tf.boolean_mask(age_values, finite_age_indices)
  mean_age = tft.mean(finite_age_values)
```

**Comment by thisisandreeeee** [comment]
Oh wow, that's quite interesting. Is a permanent fix expected anytime soon?

**Comment by zoyahav** [comment]
I don't think so, we've had some discussions about this but it's not yet clear what's the right (least surprising) result, but we are tracking it and are intending to fix it at some point.
For example, TensorFlow and numpy mean methods return NaN in this case, but we could also ignore these values.

**Comment by thisisandreeeee** [comment]
I see. Thank you for your help. I will mark this issue as closed in the meantime.

**Comment by amarchin** [comment]
Let's say I have this data frame saved in a parquet format

```python
import numpy as np
import pandas as pd

data = pd.DataFrame(dict(
    a=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], 
    b=[1.0, 1.0, 1.0, np.NaN, 0.0, np.NaN],
    c=[0.9, np.NaN, 1.0, 0.0, 0.0, 0.0]
))

data.to_parquet('data.parquet')
```

along with a dictionary that tells me which values I should use for the imputation. Then I can write a preprocessing function.

```python
import tensorflow as tf

impute_dictionary = dict(b=1.0, c=0.0)

def preprocessing_fn(inputs):
    outputs = inputs.copy()

    for key, value in impute_dictionary.items():
        outputs[key] = tf.where(
            tf.math.is_nan(outputs[key]),
            tf.constant(value, shape=outputs[key].shape),
            outputs[key]
        )

    return outputs
```

and use it in Apache Beam pipeline

```python
import tempfile

import apache_beam as beam
import tensorflow_transform.beam as tft_beam
from tensorflow_transform.tf_metadata import dataset_metadata, schema_utils

temp = tempfile.gettempdir()

RAW_DATA_FEATURE_SPEC = dict(
    [(name, tf.io.FixedLenFeature([], tf.float32)) for name in ['a', 'b', 'c']] 
)

RAW_DATA_METADATA = dataset_metadata.DatasetMetadata(schema_utils.schema_from_feature_spec(RAW_DATA_FEATURE_SPEC))

with beam.Pipeline() as pipeline:
    with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
        raw_data = pipeline | 'ReadTrainData' >> beam.io.ReadFromParquet('data.parquet')
        raw_dataset = (raw_data, RAW_DATA_METADATA)
        transformed_dataset, transform_fn = (raw_dataset | tft_beam.AnalyzeAndTransformDataset(preprocessing_fn))
        transformed_data, transformed_metadata = transformed_dataset
        transformed_data_coder = tft.coders.ExampleProtoCoder(transformed_metadata.schema)
```

However I get this error: `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

@zoyahav you mentioned in https://github.com/tensorflow/transform/issues/103 I should use `SparseTensor` but in which way? I tried to change the schema using `tf.io.VarLenFeature` and `tf.sparse.to_dense` but I get errors anyway

`ValueError: Feature a (Tensor("SparseToDense:0", shape=(None, None), dtype=float32)) had invalid shape (None, None) for FixedLenFeature: apart from the batch dimension, all dimensions must have known size`.

Many thanks!

**Comment by amarchin** [comment]
The problem was that I was setting the shape in tf.constant(value, shape=outputs[key].shape). Using tf.constant(value) instead solved that error. However I got '`average_loss': nan` and `'loss': nan`. So I am not sure the imputation is working.

**Comment by zoyahav** [comment]
Is the snippet above the code you're using? Is it possible that 'a' also has nans but it's not in your impute_dictionary?

Also note that a nan in loss doesn't necessarily indicate that your preprocessing was not successful, I suggest inspecting the transformed data to verify.

**Comment by amarchin** [comment]
That one was a reproducible example with some of the real code. I tried only to focus on the `preprocessing_fn`. I checked if the imputation was working correctly, it did. Anyway I had troubles with the `tft.scale_to_0_1` to rescale the features.

```python
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_transform as tft

NUMERIC_FEATURE_KEYS = ['a', 'b', 'c']
impute_dictionary = dict(b=1.0, c=0.0)


@tf.function
def preprocessing_fn(inputs):
    """Preprocess input columns into transformed columns."""
    # Since we are modifying some features and leaving others unchanged, we
    # start by setting `outputs` to a copy of `inputs.
    outputs = inputs.copy()

    for key, value in impute_dictionary.items():
        outputs[key] = tf.where(
            tf.math.is_nan(outputs[key]),
            tf.constant(value, dtype=tf.float32),
            outputs[key]
        )

    # Scale numeric columns to have range [0, 1].
    for key in NUMERIC_FEATURE_KEYS:
        outputs[key] = tft.scale_to_0_1(outputs[key])

    return outputs


if __name__ == '__main__':
    data = pd.DataFrame(dict(
        a=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], 
        b=[1.0, 1.0, 1.0, np.NaN, 0.0, np.NaN],
        c=[0.9, np.NaN, 1.0, 0.0, 0.0, 0.0]
    ))
    x = {}
    for col in data.columns:
        x[col] = tf.constant(data[col], dtype=tf.float32, name='col')
    print(preprocessing_fn(x))
```

This is the error:
```
2020-02-04 16:50:15.438863: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 16:50:15.454990: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa5709c68c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-04 16:50:15.455019: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-02-04 16:50:17.492870: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: You must feed a value for placeholder tensor 'scale_to_0_1_1/min_and_max/Placeholder_1' with dtype float
	 [[{{node scale_to_0_1_1/min_and_max/Placeholder_1}}]]
Traceback (most recent call last):
  File "/Users/andrea.marchini/Hackathon/tfx_test/foo.py", line 35, in <module>
    print(preprocessing_fn(x))
  File "/Users/andrea.marchini/.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/Users/andrea.marchini/.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 638, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/Users/andrea.marchini/.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/Users/andrea.marchini/.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Users/andrea.marchini/.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/Users/andrea.marchini/.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  You must feed a value for placeholder tensor 'scale_to_0_1_1/min_and_max/Placeholder_1' with dtype float
	 [[node scale_to_0_1_1/min_and_max/Placeholder_1 (defined at /.local/share/virtualenvs/tfx_test-jg7eSsGQ/lib/python3.7/site-packages/tensorflow_transform/analyzer_nodes.py:102) ]] [Op:__inference_preprocessing_fn_159]

Function call stack:
preprocessing_fn
```

**Comment by zoyahav** [comment]
Right, you can't just call the preprocessing_fn directly to look at the transformed data, the transformation relies on TFT computing the statistics in a deferred manner.

In order to print the transformed data in your example above you would have to have a beam pipeline  (like you did [here](https://github.com/tensorflow/transform/issues/152#issuecomment-581537080)), and look at the data while in the beam pipeline:

```
...

import pprint

with beam.Pipeline() as pipeline:
    with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
        raw_data = pipeline | 'ReadTrainData' >> beam.io.ReadFromParquet('data.parquet')
        raw_dataset = (raw_data, RAW_DATA_METADATA)
        transformed_dataset, transform_fn = (raw_dataset | tft_beam.AnalyzeAndTransformDataset(preprocessing_fn))
        transformed_data, transformed_metadata = transformed_dataset

        transformed_data | beam.Map(pprint.pprint)
```

I tried running that with your code snippets and got:

```
{'a': 0.0, 'b': 1.0, 'c': 0.9}
{'a': 0.2, 'b': 1.0, 'c': 0.0}
{'a': 0.4, 'b': 1.0, 'c': 1.0}
{'a': 0.6, 'b': 1.0, 'c': 0.0}
{'a': 0.8, 'b': 0.0, 'c': 0.0}
{'a': 1.0, 'b': 1.0, 'c': 0.0}
```

**Comment by amarchin** [comment]
Ok, I see. :man_facepalming: 

 Thank you very much!

**Comment by IvanNardini** [comment]
Hi, 

i'm trying to replicate the example above but I have a csv file. 

Below my code 

`
# Preprocessing
import pandas as pd

# Tensorflow
import tensorflow as tf
import tensorflow_transform as tft
import apache_beam as beam
import tensorflow_transform.beam as tft_beam
from tensorflow_transform.tf_metadata import dataset_metadata, schema_utils

BASE_DIR_PATH = os.getcwd()
DATA_DIR_PATH = os.path.join(BASE_DIR_PATH, '../data')
TEST_DATA_PATH = os.path.join(DATA_DIR_PATH, 'test_settings_data.csv')

data = pd.DataFrame(dict(
    a=[1.0, 2.0, 3.0, 4.0, 5.0, np.NaN], 
    b=[1.0, 1.0, 1.0, 2.0, np.NaN, 0.0],
    c=[0.0, 1.0, 1.0, 1.0, 0.0, 0.0]
))

data.to_csv(TEST_DATA_PATH, index=False)

raw_train_dataset = tf.data.experimental.make_csv_dataset(
      TEST_DATA_PATH,
      batch_size=6,
      na_value="NaN",
      num_epochs=1,
      ignore_errors=True)

#Set Features
NUMERIC_FEATURE_KEYS = ['a', 'b', 'c']

# Calculate means for imputing continuous variables
means = data.describe().transpose()['mean'].to_dict()

# Define preprocessing function
def preprocessing_fn(inputs): 
    outputs = inputs.copy()

    for key, value in means.items():
        outputs[key] = tf.where(tf.math.is_nan(outputs[key]),
                                tf.constant(value, dtype=tf.float32), 
                                outputs[key]) 

    for key in NUMERIC_FEATURE_KEYS:
        outputs[key] = tft.scale_to_0_1(outputs[key])

    return outputs

# Use Apache Beam pipeline to run preprocessing_fn
temp = tempfile.gettempdir()

# Define Schema variables
RAW_DATA_FEATURE_SPEC = dict(
    [(name, tf.io.FixedLenFeature([], tf.float32)) for name in ['a', 'b', 'c']] 
)
RAW_DATA_METADATA = dataset_metadata.DatasetMetadata(schema_utils.schema_from_feature_spec(RAW_DATA_FEATURE_SPEC))

#Set Beam pipeline
with beam.Pipeline() as pipeline:
    with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
        
        #Step 1: Read data
        raw_data = (pipeline 
        | 'ReadTrainData' >> beam.io.ReadFromText(TEST_DATA_PATH))
        
        raw_dataset = (raw_data, RAW_DATA_METADATA)
             
        #Step 2: Pass raw_dataset 
        transformed_dataset, transform_fn = (raw_dataset 
        | 'TrasformTrainData' >> tft_beam.AnalyzeAndTransformDataset(preprocessing_fn))
        
        transformed_data, transformed_metadata = transformed_dataset
        transformed_data | beam.Map(pprint.pprint)
`

Below the error I get

`
TypeError: string indices must be integers [while running '[42]: TrasformTrainData/TransformDataset/Transform']
`

But I can't see the issue. 

Could you give me an insight about that? Thanks

**Comment by zoyahav** [comment]
Could you please provide a full stacktrace?
