### ISSUE TITLE
scale_to_z_score_per_key with elementwise=True

### ISSUE THREAD

**Issue by K-Niu** [tensorflow/transform#154]
I've noticed that trying to use `tft.scale_to_z_score_per_key` with `elementwise=True` raises:
```
NotImplementedError: Per-key elementwise reduction not supported
```

I have a vector field in my data that can be missing (and a missing indicator field), and I would like to scale only the non-missing part of the data using my `preprocessing_fn`. 

---
This is my input spec:
```
INPUT_FEATURE_SPEC = {
        "vector": tf.io.FixedLenFeature([300], tf.float32), # 300 dimensional vector that is all 0's when missing
        "vector_missing": tf.io.FixedLenFeature([], tf.int64), # 1 if vector is missing else 0
}
```

and I would like to do something like:
```
def preprocessing_fn(input):
    vector_missing = tf.map_fn(
        lambda x: tf.cond(tf.equal(x, 1), lambda: "yes", lambda: "no"),
        input["vector_missing"],
        dtype=tf.string
    )
    # Use per_key version to exclude missing vectors in calculation of mean and std
    vector_scaled = tft.scale_to_z_score_per_key(input["vector"], key=vector_missing, elementwise=True)

    output = {
        "vector": vector_scaled,
        "vector_missing": input["vector_missing"],
    }

    return output
```

Is there anyway around this?

---
I've tried something like this:
```
def preprocessing_fn(input):
    vector_missing = tf.map_fn(
        lambda x: tf.cond(tf.equal(x, 1), lambda: "yes", lambda: "no"),
        input["vector_missing"],
        dtype=tf.string
    )

    # Try to apply scale_to_z_score_per_key with elementwise=False to each element of each vector
    vector_scaled = tf.transpose(
        tf.map_fn(
            lambda i: tft.scale_to_z_score_per_key(input["vector"][:, i], key=vector_missing, elementwise=False),
            tf.range(300),
            dtype=tf.float32
        ),
    )

    output = {
        "vector": vector_scaled,
        "vector_missing": input["vector_missing"]
    }

    return output
```
but I get the following error:
```
ValueError: The tensor_or_op Tensor("scale_to_z_score_per_key/mean_and_var_per_key/UniqueWithCounts:0", shape=(None,), dtype=string) depended on a placeholder (Tensor("scale_to_z_score_per_key/mean_and_var_per_key/UniqueWithCounts/map/TensorArrayV2Stack/TensorListStack:0", shape=(None,), dtype=string)) that was not in the input_signature.  This may have be caused by manually adding a placeholder to the graph
```

**Comment by michaelwunder** [comment]
The usual way to map per-key operations in an elementwise manner is to tf.unstack the vectors, perform the per-key mapping on each column into a new list, then tf.stack them together again. 

Perhaps for your use case it would be preferable to use a weighted mean_and_var and then scale your vectors with the resulting one-dimensional vector? You could make a new function that looks like the existing analyzers._mean_and_var except you pass in weight of one where the vector is present and zero where it is missing.

**Comment by K-Niu** [comment]
Thanks for the reply @michaelwunder! Is this what you mean by stacking and unstacking?
```
def preprocessing_fn(input):
    vector_missing = tf.map_fn(
        lambda x: tf.cond(tf.equal(x, 1), lambda: "yes", lambda: "no"),
        input["vector_missing"],
        dtype=tf.string
    )

    vector_values = tf.unstack(input["vector"], axis=1)
    vector_values_scaled = [tft.scale_to_z_score_per_key(x, key=vector_missing, elementwise=False) for x in vector_values]
    vector_scaled = tf.stack(vector_values_scaled, axis=1)


    output = {
        "vector": vector_scaled,
        "vector_missing": input["vector_missing"],
    }

    return output
```

After trying this, my tf transform job is stuck in:
```
INFO     2020-01-22 23:21:35 Assets added to graph.
INFO     2020-01-22 23:21:35 No assets to write.
INFO     2020-01-22 23:21:44 SavedModel written to: gs://.../saved_model.pb
```
Does this mean my graph is too big? I have three vector features I'm trying to scale, with lengths 300, 768, and 128.

**Comment by K-Niu** [comment]
Also how would I go about modifying `analyzers._mean_and_var`?  

It looks like I could create a `_weighted_mean_and_var` function that is like `analyzers._mean_and_var` but takes in weights? And then create a function `_weighted_scale_to_z_score_internal` that is similar to `mappers._scale_to_z_score_internal`. And then finally create a `weighted_scale_to_z_score` mapper that calls is similar to `mappers.scale_to_z_score` and calls `_weighted_scale_to_z_score_internal`?

**Comment by K-Niu** [comment]
Actually, I was able to solve this with some inspiration from #152 

```
def preprocessing_fn(input):
    vector_missing = tf.map_fn(
        lambda x: tf.cond(tf.equal(x, 1), lambda: True, lambda: False),
        input["vector_missing"],
        dtype=tf.bool
    )

    vector_mean = tft.mean(tf.boolean_mask(input["vector"], vector_missing), reduce_instance_dims=False)
    vector_var = tft.var(tf.boolean_mask(input["vector"], vector_missing), reduce_instance_dims=False)
    vector_scaled = (input["vector"] - vector_mean) / tf.sqrt(vector_var)

    output = {
        "source": input["source"],
        "source_id": input["source_id"],
        "vector": vector_scaled,
        "vector_missing": input["vector_missing"]
    }

    return output
```

**Comment by michaelwunder** [comment]
This example has inspired some discussion about opening up the weighted option for mean/var, which shouldn't be too complicated although it depends on the definition of "missing". Until that happens, this solution is probably the elegant one for your particular problem, along with taking care of columns with fixed values, etc.

**Comment by K-Niu** [comment]
Sounds good, thanks for the help! Closing this issue for now then
