### ISSUE TITLE
tf-transform breaks with tf.lookup

### ISSUE THREAD

**Issue by schmidt-jake** [tensorflow/transform#155]
Consider this toy model:
```python
import tensorflow as tf
import tensorflow_transform as tft

i = tf.keras.Input(name='x', shape=(121,3))
o = tf.keras.layers.LSTM(1, name='o')(i)
trained_model = tf.keras.Model(i, o)
trained_model.compile('adam', 'mse')

tft_output = tft.TFTransformOutput('...')

@tf.function(input_signature=[tf.TensorSpec(shape=(None, 121), dtype=tf.float32) for _ in range(3)])
def serve_fn(x1, x2, x3):
    transformed_x = tft_output.transform_raw_features({
        'x1': x1,
        'x2': x2,
        'x3': x3
    }, drop_unused_features=True)
    print(x)
    y = trained_model(x)
    return {'y': y}

trained_model.save('tmp', save_format='tf', signatures=serve_fn)
```
The tft_transform `preprocessing_fn` is:
```python
def preprocessing_fn(inputs: dict) -> dict:
    print(inputs)
    return {
        'x': tf.stack([
            tft.scale_to_z_score(utils.clip(utils.fillna(inputs['x1'], 0), lower=0, upper=20000)),
            tft.scale_to_z_score(utils.clip(utils.fillna(inputs['x2'], 0), lower=0, upper=200)),
            tft.scale_to_z_score(utils.clip(utils.fillna(inputs['x3'], 0), lower=0, upper=10000))
        ], axis=-1),
        'mode_state': inputs['mode_state'], # this is the target
        'sample_weight': utils.balanced_sample_weight(tf.squeeze(inputs['mode_state'], axis=-1))
    }
```

This runs fine. I can load this model with `loaded_model = tf.keras.models.load_model('tmp')` and `model.summary()` yields:
```
Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
x (InputLayer)               [(None, 121, 3)]          0         
_________________________________________________________________
o (LSTM)                     (None, 1)                 20        
=================================================================
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
```
Here is the `signature_def`:
```
saved_model_cli show \
    --dir tmp \
    --tag_set serve \
    --signature_def serving_default
```

```
The given SavedModel SignatureDef contains the following input(s):
  inputs['rop'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 121)
      name: serving_default_rop:0
  inputs['rotary_speed'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 121)
      name: serving_default_rotary_speed:0
  inputs['rotary_torque'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 121)
      name: serving_default_rotary_torque:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['y'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
```

But when I call
```
saved_model_cli run \
    --dir tmp \
    --tag_set serve \
    --signature_def serving_default \
    --input_exprs 'x1=np.random.rand(10,121);x2=np.random.rand(10,121);x3=np.random.rand(10,121)'
```
I get the error:
```
Traceback (most recent call last):
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'StatefulPartitionedCall/StatefulPartitionedCall/transform/transform/inputs/F_mode_state' with dtype int64 and shape [?,1]
	 [[{{node transform/transform/inputs/F_mode_state}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mapr/houmaprdev/user/jschmidt2/.local/bin/saved_model_cli", line 10, in <module>
    sys.exit(main())
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 990, in main
    args.func(args)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 724, in run
    init_tpu=args.init_tpu, tf_debug=args.tf_debug)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/tools/saved_model_cli.py", line 425, in run_saved_model_with_feed_dict
    outputs = sess.run(output_tensor_names_sorted, feed_dict=inputs_feed_dict)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/mapr/houmaprdev/user/jschmidt2/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'StatefulPartitionedCall/StatefulPartitionedCall/transform/transform/inputs/F_mode_state' with dtype int64 and shape [?,1]
	 [[{{node transform/transform/inputs/F_mode_state}}]]
```
It seems to me that `tft_output.transform_raw_features({...}, drop_unused_features=True)` isn't dropping the `mode_state` feature from the serving graph... am I doing something wrong?

**Comment by zoyahav** [comment]
This is somewhat uncharted territory since tf.Transform's TF 2.x support is still in beta, we haven't tested everything with Keras yet.

That said, the feature spec passed to tft_output.transform_raw_features should be this:
`raw_feature_spec = tft_output.raw_feature_spec()`

Followed by:

`raw_feature_spec.pop('mode_state')`

Could you please make sure this is the case and see if that works?

I believe in your case `mode_state` is not unused therefore it would not be dropped when specifying `drop_unused_features` (+@ckkuang for drop_unused_features).

**Comment by JakeTheWise** [comment]
> the feature spec passed to tft_output.transform_raw_features
`tft_output.transform_raw_features` takes a `dict` of tensors though... not a feature spec.

**Comment by JakeTheWise** [comment]
Plus you can see from the output of `saved_model_cli show` that the exported model has the intended signature.

**Comment by JakeTheWise** [comment]
Also can you explain why you suspect "mode_state is not unused"? You can see the preprocessing_fn does not use it to calculate the transformed feature `x`.

**Comment by ckkuang** [comment]
Can you check if the model's output node depends on the the 'model_state' placeholder node? You may use tensorboard to visualize the graph produced by tf.function and see if the two nodes are connected: https://www.tensorflow.org/tensorboard/graphs#graphs_of_tffunctions

**Comment by JakeTheWise** [comment]
The issue was that I was using `tf.lookup` in my function to compute sample weights. Is there a way we can fix this?

**Comment by JakeTheWise** [comment]
@ckkuang @zoyahav I think this problem is actually more general: it happens when I apply transformations on my target feature(s). For instance, if I have a bytes_feature target that I need to integer encode for a multiclass problem, I try to use tft.compute_and_apply_vocabulary, but this creates a dependency on the target tensor placeholder that will not be available in serving.

**Comment by JakeTheWise** [comment]
@ckkuang @zoyahav @rmothukuru  any update on this?

**Comment by zoyahav** [comment]
@JakeTheWise have you tried using `tft_output.transform_features_layer`?
https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TFTransformOutput#transform_features_layer
It was introduced in TFT 0.21.2 and then improved significantly in 0.22.

**Comment by JakeTheWise** [comment]
Yes, I am aware of `transform_features_layer`, however I am trying to use tf-transform to apply logic to my targets. By adding it as a model layer, I am unaware of how to pass my targets to it without forking keras.

**Comment by zoyahav** [comment]
Right, this is a known limitation.
Currently the suggested option is to apply the layer logic to the targets in a dataset.map() call. This way you can fully control when they should be transformed.
Doing this allows you to either transform both regular features and targets in this map, or just targets, and have the layer in the model that you're defining.

In this example, all features including targets are transformed in a dataset.map:
https://github.com/tensorflow/transform/blob/3d6446e86fce5eb2d333b3df2826896374c85993/examples/census_example_v2.py#L325-L327

Alternatively, in this example we could have just has:
```
    raw_label = raw_features.pop(LABEL_KEY)
    data_labels = tft_layer({LABEL_KEY: raw_label})
    return (raw_features, data_labels)
```
And then applied the layer as part of the training/serving model as well for the rest of the features.

**Comment by JakeTheWise** [comment]
Yes, that is how I currently do it. Except in my `map` call I've been using `transform_raw_features`... I see you guys are instead using `transform_feature_layer`... is `transform_raw_features` gonna be deprecated?

**Comment by zoyahav** [comment]
We don't currently have concrete plans to deprecate `transform_raw_features `, and it will be supported as long as TFT supports TF 1.15.
Regardless, `transform_feature_layer` is the API that should be used when using Keras, and even more so as we move forward towards native TF 2.x support in TFT in the next few releases.
