### ISSUE TITLE
Is there any example of nlp, like text classification? string input, not other data preprocess outside.

### ISSUE THREAD

**Issue by yongzhuo** [tensorflow/transform#162]
Is there any example of nlp, like text classification? string input, not other data preprocess outside.

**Comment by yongzhuo** [comment]
I think a tookit of postprocessing is needed, like task of ner, tensorflow transform Similarity!

**Comment by zoyahav** [comment]
Please expand on what it is you're looking for.
This is one blog post about using tf.Transform for NLP (BERT):
https://blog.tensorflow.org/2020/03/part-1-fast-scalable-and-accurate-nlp-tensorflow-deploying-bert.html

**Comment by rmothukuru** [comment]
@yongzhuo,
Can you please respond to @zoyahav's comment. Thanks!

**Comment by yongzhuo** [comment]
@zoyahav @rmothukuru ok, I see, thanks!
like this:
```
vocab_file_path = load_bert_layer().resolved_object.vocab_file.asset_path
bert_tokenizer = text.BertTokenizer(vocab_lookup_table=vocab_file_path, 
                                    token_out_type=tf.int64, 
                                    lower_case=do_lower_case)
...
input_word_ids = tokenize_text(text)
input_mask = tf.cast(input_word_ids > 0, tf.int64)
input_mask = tf.reshape(input_mask, [-1, MAX_SEQ_LEN])

zeros_dims = tf.stack(tf.shape(input_mask))
input_type_ids = tf.fill(zeros_dims, 0)
input_type_ids = tf.cast(input_type_ids, tf.int64)```
