### ISSUE TITLE
Unit testing the preprocessing_fn

### ISSUE THREAD

**Issue by sainathadapa** [tensorflow/transform#167]
Can you provide some examples that illustrate the way to unit test the preprocessing functions?

**Comment by rmothukuru** [comment]
@sainathadapa,
Please check if [this link](https://github.com/tensorflow/transform/blob/334c0750a62000155366bc8257f950f420dec3f1/tensorflow_transform/inspect_preprocessing_fn_test.py) is helpful. Thanks!

**Comment by zoyahav** [comment]
Check out this test for a simple example of a preprocessing_fn test:
https://github.com/tensorflow/transform/blob/4f573e04330b25e957df8f653647b79a52a545ee/tensorflow_transform/beam/impl_test.py#L493-L523

Note that the test class is inheriting from [`tft.beam.tft_unit.TransformTestCase`](https://github.com/tensorflow/transform/blob/4f573e04330b25e957df8f653647b79a52a545ee/tensorflow_transform/beam/tft_unit.py#L78).

**Comment by sainathadapa** [comment]
Thank you!
