### ISSUE TITLE
Type hint violation when the inputs to AnalyzeAndTransformDataset are tf tensors

### ISSUE THREAD

**Issue by sainathadapa** [tensorflow/transform#168]
From the guide (https://www.tensorflow.org/tfx/tutorials/transform/simple), I'm running the following piece of code:

```
with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
    transformed_dataset, transform_fn = (  # pylint: disable=unused-variable
        (raw_data, raw_data_metadata) | tft_beam.AnalyzeAndTransformDataset(
            preprocessing_fn))
```

I changed the raw_data to contain some SparseTensor values. Then, I get the following error:

```
TypeCheckError: Type hint violation for 'ApplySavedModel': requires List[Dict[Any, Union[List[Any], bytes, float, generic, int, ndarray, str]]] but got List[Dict[str, SparseTensor]] for batch
```

Should the inputs to `AnalyzeAndTransformDataset` not be tf tensors?

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by zoyahav** [comment]
No, the inputs to `AnalyzeAndTransformDataset` should be primitive data (as shown in the link above).
Sparse data can be represented by a list of values (note that tf.Transform only supports left-aligned or 'ragged' sparse tensors), and should be listed as VarLenFeatures in the feature spec.
For example, [see the advanced tutorial](https://www.tensorflow.org/tfx/tutorials/transform/census#define_our_features_and_schema).

You may find the TFT coders useful here, they take a common representation (CSV/tf.Example) and format it in a way that tf.Transform can process:
https://www.tensorflow.org/tfx/transform/api_docs/python/tft/coders

**Comment by sainathadapa** [comment]
Thank you!
