### ISSUE TITLE
ptransform_analyzer: unexpected output shape and behaviour

### ISSUE THREAD

**Issue by iainwo** [tensorflow/transform#173]
Hi team,

# Motivation
Recently, I've been attempting to augment TFX and TFT with Apache Beam and I have run into an issue - or perhaps, a lack of understanding.
My motivation is to produce a reusable hermetic artifact to satisfy common inference tasks like model scoring and deployment. Within that artifact will include the mechanics for preprocessing, feature-engineering and modelling.

# Issue
The shape and behaviour produced by tft.ptransform_analyzer seems contradictory to the documentation within the method signature.
- It seems, that applications of ptransform_analyzer which produce tensors with parameterized shapes that are greater-than rank-0, instead produces tensors of the intended rank but with shapes that are stretched by a constant factor

# Related Issue
There is another similar issue open: https://github.com/tensorflow/transform/issues/166.

Would love to get your input,
- Thanks, Iain

# Code Sketch
The code looks something like this, at the bottom of the issue I will include a Colab notebook with a full implementation.

## Control preprocessing_fn()
A straight pass-through replicates the same number of raw ingested samples.
```python
def preprocessing_fn(inputs):
  return inputs # producing tensor shape (9909, 18)
```

## Trial preprocessing_fn()
A beam transformation employed on the raw samples produces duplicated output.
```python
def preprocessing_fn(inputs):
  outputs = dict()
  preprocessed_data = tft.ptransform_analyzer(
      inputs=[
        _fill_in_missing(inputs['trip_seconds']),
        _fill_in_missing(inputs['fare']),
      ],
      output_dtypes=[tf.string for feat in _ALL_COLUMNS],
      output_shapes=[(None,) for feat in _ALL_COLUMNS],
      ptransform=Preprocessing(),
      name='PtransformAnalyzerPreprocessingTrial',
  )
  for label, tup in enumerate(preprocessed_data):
    outputs[f'beam_feature_{label}'] = tup

  return outputs # producing shape of (138740, 2). expected to be (9909, 2)
```

## Ratio of preprocessing_fn#1 vs preprocessing_fn#2
```python
>>> trial_df.shape[0]/(control_df.shape[0]+1)
14.0
```

# Colab Notebook
https://gist.github.com/iainwo/ccfd4d37bee12994ab734007c0cebcb1

**Comment by zoyahav** [comment]
In tf.Transform we differentiate between analyzers and mappers:

- Analyzers require a pass over the dataset, and eventually perform a reduce over it producing tensors of some size (independent from the input dataset size). Example: `tft.max` does a full pass of the dataset and produces a single integer.
- Mappers define a TF compute which maps inputs to outputs, usually preserving the input dataset size. Most of the time mappers use analyzers in their implementation in order to compute required reduces. Example: `tft.scale_to_0_1` is a mapper which uses the min and max analyzers to compute these constants used for the scaling mapping.

`tft.ptransform_analyzer` is an analyzer, so it performs a reduction and the size of its results is not dependent on the dataset size, which is why you're observing different sizes between trial and control in your code.

Using the results of an analyzer as in your code is generally incorrect, as the returned tensors from the preprocessing_fn must be batched consistently in order to avoid leaking example information:
`outputs[<name>] = <output_of_analyzer>`

Could you expand on what kind of mapping you're looking to do on your mapping? that would help us advise you on how to achieve that.

**Comment by iainwo** [comment]
Hey @zoyahav,

Thanks for the explanation. Makes sense.

## Explanation
> Could you expand on what kind of mapping you're looking to do on your mapping? that would help us advise you on how to achieve that.

I would like to inject beam dofns/pardos/ptransforms into the TFX Transform Component to perform stateless (mapper) and stateful (analyzer) operations on the raw data ingested into the TFX Pipeline (via ExampleGen); that is, perform feature-engineering prior to modelling or serving.

An addendum, being that the behaviour of the feature-engineering (i.e w.r.t descriptive statistics like mean, stddev, min) remains consistent between different datasets (e.g train/val/test/inference).

### Examples of `mapper` (i.e stateless) Operations

- arithmetic operations on a subset of features (e.g add two columns)
- simple logical operations on a subset of features (e.g equivalence, exclusive-or, or if-based control flow logic)
- string parsing
- typecasting (e.g convert a numerical to a string)
- complex processing (e.g beam.Map -> beam.GroupByKey -> beam.Filter)

### Examples of `analyzer` (stateful) Operations

- computation involving an unsupported descriptive statistic

Overall I am looking for a generalized preprocessing and feature-engineering solution that is integrated with the TFX framework that is implemented using a scaled and robust data processing technology.

**Comment by zoyahav** [comment]
Thanks @iainwo.
Note that in Transform, we implement analyzers using beam dofns/pardos/ptransforms, but the mappers are implemented using pure TensorFlow.
The reason for that is that the mappers eventually get encoded in the transformation graph which is applied later on the data for training and inference.

As for the list of mappers that you described:
> arithmetic operations on a subset of features (e.g add two columns)

Can be done with TF ops
> simple logical operations on a subset of features (e.g equivalence, exclusive-or, or if-based control flow logic)

Can be done with TF ops and control flow ops (tf.cond, etc.)
> string parsing

Can be done with TF ops
> typecasting (e.g convert a numerical to a string)

Ditto
> complex processing (e.g beam.Map -> beam.GroupByKey -> beam.Filter)

This can't be done using beam in the mappers. Filtering can be done using TF ops (dropping an instance from a batch) while it could be a bit challenging.
We would normally recommend doing these types of mappings upstream in a custom ExampleGen.

Hope this helps.

**Comment by iainwo** [comment]
Awesome, thanks @zoyahav. Yep that gives me a good sense of what my options are, and what would be conventional.

Closing the issue. Appreciate the help!
