### ISSUE TITLE
Cannot z_scale_normalize variable-sized images

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/transform#175]
tensorflow==2.1.0
tensorflow-transform==0.21.0

```python
@tf.function
def parse_png(png: tf.Tensor) -> tf.Tensor:
    pixels = tf.io.decode_png(png, channels=3)
    return pixels
            
def preprocessing_fn(inputs: dict) -> dict:
    pixels = tf.map_fn(parse_png, tf.squeeze(inputs['png'], axis=1), dtype=tf.uint8, infer_shape=True)
    pixels = tft.scale_to_z_score(pixels)
    pixels = tf.map_fn(lambda t: tf.reshape(t, [-1]), pixels, dtype=tf.float32) # flatten each image
    pixels = tf.sparse.from_dense(pixels)
    return {'pixels': pixels} # return the normalized variable-length feature
```
Running `tft_beam.AnalyzeDataset(preprocessing_fn)` raises this error:
```
PartialTensorShape: Incompatible shapes during merge: [14,14,3] vs. [11,11,3]
	 [[{{node transform/map/TensorArrayV2Stack/TensorListStack}}]]
```

When I comment out the line with `tft.scale_to_z_score(pixels)` however, the code works.

**Comment by zoyahav** [comment]
@JakeTheWise could you provide a working repro (perhaps in the form of a colab notebook) so that we can take a look at this?

**Comment by zoyahav** [comment]
You could also try setting the batch_size explicitly to 1 to see if the issue is that the map_fns aren't maintaining the input batch_size.
See desired_batch_size in https://www.tensorflow.org/tfx/transform/api_docs/python/tft_beam/Context.

**Comment by rmothukuru** [comment]
@JakeTheWise,
Can you please respond to @zoyahav's comments. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
