### ISSUE TITLE
Question: setting prediction with keras model using transform function

### ISSUE THREAD

**Issue by Shishir-Suman** [tensorflow/transform#190]
Have been trying to setup prediction pipeline for a keras model that uses transform function generated during model training. The generated transform function contains additional attributes which are not available during prediction and objective is to drop them and apply transforms on remaining features before running the model prediction.  

Came across https://www.tensorflow.org/tfx/guide/keras#keras_module_file_with_transform. The link provides an example 

```def _get_serve_tf_examples_fn(model, tf_transform_output):
  model.tft_layer = tf_transform_output.transform_features_layer()

  @tf.function
  def serve_tf_examples_fn(serialized_tf_examples):
    feature_spec = tf_transform_output.raw_feature_spec()
    feature_spec.pop(_LABEL_KEY)
    parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)

    transformed_features = model.tft_layer(parsed_features)

    return model(transformed_features)

  return serve_tf_examples_fn
```

and is referred later via

```
signatures = {
      'serving_default':
          _get_serve_tf_examples_fn(model,
                                    tf_transform_output).get_concrete_function(
                                        tf.TensorSpec(
                                            shape=[None],
                                            dtype=tf.string,
                                            name='examples')),
  }
  model.save(fn_args.serving_model_dir, save_format='tf', signatures=signatures)
```

In here, executing tf_transform_output.transform_raw_features(raw_features) standalone gave me eager exception errors. Is that not supported yet. 

Thanks in advance.

**Comment by rmothukuru** [comment]
@Shishir-Suman,
Can you please share your code and the error log. Thanks!

**Comment by rmothukuru** [comment]
@Shishir-Suman,
Can you please respond to the above comment. Thanks!

**Comment by Shishir-Suman** [comment]
@rmothukuru Sorry for a delayed reply. Most likely was using tf transform fn in an unsupported way earlier and found an alternative approach to implement transformation pipeline using Dense Features and map function..

Processing fn was very simple and applied z-transform to a numerical column.

`def preprocessing_fn(inputs):
    """Preprocess input columns into transformed columns."""
    # Since we are modifying some features and leaving others unchanged, we
    # start by setting `outputs` to a copy of `inputs.
    outputs = inputs.copy()
    for key in NUMERIC_FEATURE_COLS:
        outputs[key] = tft.scale_to_z_score(outputs[key])
    return outputs`

This was then used to save the transform output.
`# Read in raw data and convert using CSV converter
raw_data = pipeline | "read_transactions" >> beam.io.Read(bq_source)
raw_data | beam.Map(print)
# Combine data and schema into a dataset tuple
raw_dataset = (raw_data, raw_data_metadata)
(
    transformed_dataset,
    transform_fn,
) = raw_dataset | tft_beam.AnalyzeAndTransformDataset(preprocessing_fn)
transformed_data, transformed_metadata = transformed_dataset`

I was trying to load the transform output to directly transform a dict input as in
`transform_fn = tft.TFTransformOutput("output_mock")
raw_data = {'country': 'Sao Tome and Principe', 'longitude': 6.733343, 'label': 1}
transform_fn.transform_raw_features(raw_data)`

The above step threw the following errors
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shishir.suman/.virtualenvs/tensorflow/lib/python3.7/site-packages/tensorflow_transform/output_wrapper.py", line 169, in transform_raw_features
    self.transform_savedmodel_dir, raw_features))
  File "/Users/shishir.suman/.virtualenvs/tensorflow/lib/python3.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 429, in partially_apply_saved_transform_internal
    saved_model_dir, logical_input_map, tensor_replacement_map)
  File "/Users/shishir.suman/.virtualenvs/tensorflow/lib/python3.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 274, in _partially_apply_saved_transform_impl
    input_map=input_map)
  File "/Users/shishir.suman/.virtualenvs/tensorflow/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1462, in import_meta_graph
    **kwargs)[0]
  File "/Users/shishir.suman/.virtualenvs/tensorflow/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1472, in _import_meta_graph_with_return_elements
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.`

**Comment by zoyahav** [comment]
This should work:
```
tft_output = tft.TFTransformOutput(...)
with tf.Graph().as_default():
  raw_data = ...
  transformed_data = tft_output.transform_raw_features(raw_data)
```

Otherwise, eager mode is only supported for Keras models, and in that case you should use:
```
tft_output = tft.TFTransformOutput(...)
tft_layer = tft_output.transform_features_layer()
transformed_data = tft_layer(raw_data)
```

**Comment by sumanshishir** [comment]
thank you!

**Comment by Shishir-Suman** [comment]
thank you. this works!

**Comment by Shishir-Suman** [comment]
When we apply transform_features_layer function, we haven't even declared keras model yet. Its just processing, so could you please elaborate on eager mode dependence on keras models.

**Comment by zoyahav** [comment]
The TFT layer should work independently from a keras model. Applying the tft_layer to data simply applies the transformations to your raw data, and should just work in eager mode.

**Comment by rmothukuru** [comment]
@Shishir-Suman,
Can you please respond to @zoyahav's comments. Thanks!

**Comment by hardianlawi** [comment]
What is the recommended way to export TFT function that has been generated during training with keras model for serving? There is [a tutorial from TF website](https://www.tensorflow.org/tfx/tutorials/transform/census#train_evaluate_and_export_our_model) which shows us how to do it with estimator, but I can't find any that shows how to do it with keras model.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
