### ISSUE TITLE
tft.quantiles doesn't ignore NaN values

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#199]
I am running some experiments where I compute quantiles of some rate features (so some denominators may be zero, resulting in NaNs) and then feed this into `tft.apply_buckets_with_interpolation`. The behavior I would expect is that `tft.quantiles` computes the quantiles for the non-NaN values, and then `tft.apply_buckets_with_interpolation` will interpolate the non-NaN values, and impute 0.5 for the NaN values.

However, when I do this, I get an error like:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 1 out of bounds. [[node transform/transform/buckets_with_interpolation_600/strided_slice_3 (defined at /site-packages/tensorflow_transform/saved/saved_transform_io.py:284) ]]
```

Tracing this in the code, it seems like some of my features must have all NaNs for the quantiles (not sure how this can happen since the features are not all NaNs). Then in `apply_buckets_with_interpolation` all of the non-finite bucket boundaries get filtered out, resulting in 0 bucket boundaries.

I confirmed that the issue is related to NaNs by replacing the `tf.math.divide` in my rate computation with `tf.math.divide_no_nan` and the error went away. But this seems like not the ideal solution from a correctness standpoint.

**Comment by askerry** [comment]
I agree we should return a better error in `apply_buckets_with_interpolation` when all boundaries are NaN, but I think the deeper question is why the quantile boundaries (computed by tft.quantiles) are being computed to be all NaN if there are non-NaN features in the data.

**Comment by cyc** [comment]
> I think the deeper question is why the quantile boundaries (computed by tft.quantiles) are being computed to be all NaN if there are non-NaN features in the data.

I am not sure. I suspect that if the NaN frequency is high enough you might have a batch with NaNs in the summary, and then perhaps the NaNs are not getting handled well during the accumulation phase.

I'm not familiar enough with the machinery of QuantilesCombiner to give a definitive answer, but it should be doable to try to reproduce the issue.

**Comment by askerry** [comment]
Yep, this easily reproduces in a unit test. We're looking into excluding the NaNs from the quantile calculation.

**Comment by iindyk** [comment]
fixed by https://github.com/tensorflow/transform/commit/ea54bc25cfe3f2a2e2ad35892936fc7b8d18c8f0
