### ISSUE TITLE
CI availability and enablement on s390x

### ISSUE THREAD

**Issue by Sidong-Wei** [tensorflow/transform#204]
Hi,

I have been trying to port TensorFlow Transform to s390x (a big-endian architecture) machine, so far I have not reached any issue with it. However, I noticed that there was not a public CI for Transform, and the PRs proposed did not seem to have public CI checks. I wonder is there an internal CI that is used for Transform? And if so, is it possible to add s390x machine into the CI list? I could provide any help needed in order to enable CI on s390x architecture. If anyone could provide some information with the CI availability and/or enablement, that will be great, thanks.

**Comment by Sidong-Wei** [comment]
Hi @gowthamkpr , would you mind sharing some feedback on this issue? Thanks in advance.

**Comment by zoyahav** [comment]
We do not have CI on github. Since TFT itself is a pure-python library it doesn't seem like adding s390x architecture to our internal CI would add much.
We do test against different environments - OS, Python version, etc.

**Comment by Sidong-Wei** [comment]
Hi @zoyahav , thanks for the kind reply. I understand that testing a pure python package on different architectures may be unnecessary, but I am just wondering what it takes if we do want to include s390x arch into the CI build. For example, we could provide hardware support if needed. Could you kindly confirm if it is possible to enable a new arch into the CI, or you think it is better to keep the way it is right now? Thank you.
