### ISSUE TITLE
Multilabel Data Processing

### ISSUE THREAD

**Issue by albertnanda** [tensorflow/transform#207]
I am trying to convert my target which is multilabel to one hot vectors by the following code:

``` python
int_value = tft.compute_and_apply_vocabulary(inputs[LABEL_KEY])
outputs[transformed_name(LABEL_KEY)] = convert_num_to_one_hot(int_value,5)

def convert_num_to_one_hot(label_tensor, num_labels):
    one_hot_tensor = tf.one_hot(label_tensor, num_labels)
    return tf.reshape(one_hot_tensor, [-1, num_labels])

I am getting the following error:
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("categories/Placeholder:0", shape=(None, 2), dtype=int64), values=Tensor("compute_and_apply_vocabulary/apply_vocab/hash_table_Lookup/LookupTableFindV2:0", shape=(None,), dtype=int64), dense_shape=Tensor("categories/Placeholder_2:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type.
```

I also have one question regarding "compute_and_apply_vocabulary", how can i get the vocab size dynamically, so that I can pass the same to tf.one_hot.

**Comment by rmothukuru** [comment]
@albertnanda,
As per [TF Transform Advanced Tutorial](https://www.tensorflow.org/tfx/tutorials/transform/census#wrap_our_input_data_in_featurecolumns), One Hot Encoding is done using the code:

```python
one_hot_columns = [
      tf.feature_column.categorical_column_with_vocabulary_file(
          key=key,
          vocabulary_file=tf_transform_output.vocabulary_file_by_name(
              vocab_filename=key))
      for key in CATEGORICAL_FEATURE_KEYS]
```

Can you please try that and let us know how it goes. Thanks!

**Comment by albertnanda** [comment]
@rmothukuru This doesn't work. This is my preprocessing_fn:
`def preprocessing_fn(inputs):
    
    outputs = {}
    tf_transform_output = tft.TFTransformOutput("/tmp/tfx-interactive-2020-10-29T06_10_09.819607-0y0igxbk/Transform/transform_graph/11/")
    vocab = tft.vocabulary(inputs[LABEL_KEY],vocab_filename="labels.txt")
    outputs[transformed_name(LABEL_KEY)] = tf.feature_column.categorical_column_with_vocabulary_file(
          key=inputs[LABEL_KEY],vocabulary_file=tf_transform_output.vocabulary_file_by_name(
              vocab_filename="labels.txt"))
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]`

So, after using this I get the error 
`NotFoundError: /tmp/tfx-interactive-2020-10-29T06_10_09.819607-0y0igxbk/Transform/transform_graph/11/transform_fn/assets; No such file or directory`

The reason is transform_fn/assets is not created until we have executed preprocessing_fn completely. I checked this by commenting out `outputs[transformed_name(LABEL_KEY)] = tf.feature_column.categorical_column_with_vocabulary_file(
          key=inputs[LABEL_KEY],vocabulary_file=tf_transform_output.vocabulary_file_by_name(
              vocab_filename="labels.txt"))` and I could see all the folders along with labels.txt in that folder.


Also, another side question is how do I set the working directory for tfx, currently I use the following command to know the location:

`context = InteractiveContext()
context.metadata_connection_config["filename_uri"]`

**Comment by zoyahav** [comment]
Yes, you can't use TFTransformOutput from within a preprocessing_fn.
It sounds like `inputs[LABEL_KEY]` is sparse in your case, is this right and/or expected?
Would converting this sparse tensor to a dense one plausible?

Another option is to just go with @rmothukuru's suggestion above and put the one-hot-encoding logic in the trainer code (outside of the preprocessing_fn).

**Comment by albertnanda** [comment]
The data has the following format, {"text":string, categories:[list of categories]}. There are 10 labels(sports, technology, politics, etc.) and each example can be assigned one or more labels. I did try to convert the same to dense by using tf.sparse_to_dense inside preprocessing_fn, but that also failed. 
I tried to follow @rmothukuru's suggestion, but that didn't work as well. Here are my functions:

`def preprocessing_fn(inputs):
    
    outputs = {}
    tf_transform_output = tft.TFTransformOutput("/tmp/tfx-interactive-2020-10-29T06_10_09.819607-0y0igxbk/Transform/transform_graph/11/")
    vocab = tft.vocabulary(inputs[LABEL_KEY],vocab_filename="labels.txt")
    outputs[transformed_name(LABEL_KEY)] = inputs[LABEL_KEY]
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]
    
   return outputs`


`def _input_fn(file_pattern, tf_transform_output, batch_size=64):
    transformed_feature_spec = (
        tf_transform_output.transformed_feature_spec().copy()
    )

    dataset = tf.data.experimental.make_batched_features_dataset(
        file_pattern=file_pattern,
        batch_size=batch_size,
        features=transformed_feature_spec,
        reader=_gzip_reader_fn,
        label_key=transformed_name(LABEL_KEY),
    )
   
    transformed_features = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    transformed_labels = transformed_features[1]
 
    
    transformed_labels= tf.feature_column.categorical_column_with_vocabulary_file(
          key=transformed_labels,
          vocabulary_file=tf_transform_output.vocabulary_file_by_name(
              vocab_filename="labels.txt"))
    return transformed_features, transformed_labels`

But this also bugged out, ValueError: key must be a string. Got: type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'>. Given key: SparseTensor(indices=tf.Tensor(

Though, I would be interested in doing the same in preprocessing_fn.

**Comment by zoyahav** [comment]
As I mentioned previously, you cannot use `tft.TFTransformOutput` in a preprocessing_fn. I'll assume it's still in your preprocesing_fn due to a copy-paste error.

The error above is because youŕe passing `transformed_labels` to `categorical_column_with_vocabulary_file` as key. It's expecting the key to be a string but you're passing it a dict of str->Tensors.
In your case for example you should be able to pass `key="labels"`.

You can do the same in your preprocessing_fn by using a correct combination of TF ops to create the onehot encoding.
Maybe this example will help: https://github.com/tensorflow/transform/blob/41c0e677c36a51076c247cf3d6cd4294c8472ec4/examples/census_example_v2.py#L152

Note that tf.one_hot expects a dense tf.Tensor, not a tf.SparseTensor which is what your feature is.
You can make a sparse tensor into a dense tensor by calling tf.sparse.to_dense(...), or tft.sparse_tensor_to_dense_with_shape(...).

**Comment by albertnanda** [comment]
I tried to follow that example, here is the output from example_gen.outputs["examples"]
`{
 'Text': array([b'Football fans looking forward to seeing the renewal of the rivalry between Cristiano Ronaldo and Lionel Messi were made to wait a while longer after the Portuguese forward was forced to miss Juventus' Champions League tie against Barcelona on Wednesday.'],dtype=object),
 'Headline': array([b"Lionel Messi scores as Cristiano Ronaldo misses Barcelona's victory over Juventus."], dtype=object),
 'categories': array([b'Sports'], dtype=object), 
}

{
 'Text': array([b'COVID-19 has changed fan behavior and accelerated three to five years of technology adoption into six months'],dtype=object),
 'Headline': array([b"How Technology Is Improving Fan Transactions at Sports Venues"], dtype=object),
 'categories': array([b'Sports', b'Science and Technology'], dtype=object), 
}`

Here is my preprocessing_fn:

`def preprocessing_fn(inputs):
    outputs = {}
    str_to_int_sparse = tft.compute_and_apply_vocabulary(inputs[LABEL_KEY])
    sparse_to_dense = tf.sparse.to_dense(str_to_int_sparse)
    transformed_label = tf.one_hot(sparse_to_dense,depth=5,on_value=1.0, off_value=0.0)
    outputs[transformed_name(LABEL_KEY)] = tf.reshape(transformed_label, [-1, 5])
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]
    

    return outputs`

And this is the error: 
`ValueError: Inconsistent batch sizes: "categories_xf" had batch dimension 256, "Headline_xf" had batch dimension 128 [while running 'Transform[TransformIndex1]/ConvertAndUnbatch']`

**Comment by zoyahav** [comment]
The issue is:
`outputs[transformed_name(LABEL_KEY)] = tf.reshape(transformed_label, [-1, 5])`

`transformed_label` has the shape (?, ?, 5), where the first `?` is the batch dimension, and the second depends on the max number of values for a single instance in `inputs[LABEL_KEY]`.
I can see that in your data above, 'categories' has size 1 for the first instance, and 2 for the second.
This means that `tf.reshape(transformed_label, [-1, 5])` would result in different batch sizes for each of the instances which is not allowed (we can't emmit instances with different batch sizes, there's no way for us to compose transformed examples in this case).

Here's a preprocessing_fn that should work for your case, though requires knowing an upper bound to the number of values for labels in your dataset:

```
MAX_LABEL_VALUE_COUNT = 2

def preprocessing_fn(inputs):
    outputs = {}
    dense_label = tft.sparse_tensor_to_dense_with_shape(
        inputs[LABEL_KEY], shape=[None, MAX_LABEL_VALUE_COUNT], default_value='Missing')
    integerized_label = tft.compute_and_apply_vocabulary(dense_label)
    outputs[transformed_name(LABEL_KEY)] = tf.one_hot(
        integerized_label,depth=5,on_value=1.0, off_value=0.0)
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]
    return outputs
```

With this version, the shape of `outputs[transformed_name(LABEL_KEY)]` is now `[None, MAX_LABEL_VALUE_COUNT, 5]`.

**Comment by albertnanda** [comment]
@zoyahav 
My max_label count is 5 i.e the len(all_labels) = 5, a document can have a maximum of 5 labels and it should be represented by a 5 dim vector i.e. for example let's say we have 5 categories A, B, C, D, E and they have been tagged as integerized as A:0,B;1,C:2,D:3,E:4. Then a document with tags A and B should be encoded as [1,1,0,0,0]. A document with all the 5 labels should be encoded as [1,1,1,1,1].
I tried your code with MAX_LABEL_VALUE_COUNT = 5 and I am getting weird results(no errors though). Here is the encoding of my first example:
```'categories_xf': array([0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)}```
My code:
``` python
MAX_LABEL_VALUE_COUNT = 5

def preprocessing_fn(inputs):
    outputs = {}
    dense_label = tft.sparse_tensor_to_dense_with_shape(
        inputs[LABEL_KEY], shape=[None, MAX_LABEL_VALUE_COUNT], default_value='Missing')
    integerized_label = tft.compute_and_apply_vocabulary(dense_label)
    outputs[transformed_name(LABEL_KEY)] = tf.one_hot(
        integerized_label,depth=5,on_value=1.0, off_value=0.0)
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]
    return outputs
```

**Comment by zoyahav** [comment]
It sounds like what you're looking for is multi-hot encoding?
What you currently have is a one-hot encoding, meaning that if the label feature in a given instance has N values, the resulting transformed feature would be of the shape [N, 5], since each value gets its own one-hot representation.

You could turn a one-hot encoding to multi-hot by using reduce_sum on the value_count axis:
```
    outputs[transformed_name(LABEL_KEY)] = tf.math.reduce_sum(
                     tf.one_hot(integerized_label,depth=5,on_value=1.0, off_value=0.0),
                     axis=1)
```

This turns 
[[1., 0., 0., 0., 0.],
 [0., 1., 0., 0., 0.]]
Into:
[1., 1., 0., 0., 0.]

**Comment by albertnanda** [comment]
Yeah, mulit-hot. Your solution works perfectly, though I had to change the order of creating vocab and sparse_to_dense transformation, because "Missing" was creating another category.
Accidently, I came across a bug in transform.
So, with the following function:
``` python
def preprocessing_fn(inputs):
    outputs = {}
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]
    return outputs
```
I get this error log:
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-41-efea3de47a8e> in <module>
----> 1 context.run(transform)

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     65       # __IPYTHON__ variable is set by IPython, see
     66       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 67       return fn(*args, **kwargs)
     68     else:
     69       absl.logging.warning(

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    180         telemetry_utils.LABEL_TFX_RUNNER: runner_label,
    181     }):
--> 182       execution_id = launcher.launch().execution_id
    183 
    184     return execution_result.ExecutionResult(

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    203                          execution_decision.input_dict,
    204                          execution_decision.output_dict,
--> 205                          execution_decision.exec_properties)
    206 
    207     absl.logging.info('Running publisher for %s',

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/orchestration/launcher/in_process_component_launcher.py in _run_executor(self, execution_id, input_dict, output_dict, exec_properties)
     65         executor_context)  # type: ignore
     66 
---> 67     executor.Do(input_dict, output_dict, exec_properties)

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/components/transform/executor.py in Do(self, input_dict, output_dict, exec_properties)
    415       label_outputs[labels.CACHE_OUTPUT_PATH_LABEL] = cache_output
    416     status_file = 'status_file'  # Unused
--> 417     self.Transform(label_inputs, label_outputs, status_file)
    418     absl.logging.debug('Cleaning up temp path %s on executor success',
    419                        temp_path)

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/components/transform/executor.py in Transform(***failed resolving arguments***)
    938                       temp_path, input_cache_dir, output_cache_dir,
    939                       compute_statistics, per_set_stats_output_paths,
--> 940                       materialization_format, len(analyze_data_paths))
    941   # TODO(b/122478841): Writes status to status file.
    942 

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tfx/components/transform/executor.py in _RunBeamImpl(self, analyze_data_list, transform_data_list, preprocessing_fn, input_dataset_metadata, transform_output_path, raw_examples_data_format, temp_path, input_cache_dir, output_cache_dir, compute_statistics, per_set_stats_output_paths, materialization_format, analyze_paths_count)
   1095                cache_base_dir=output_cache_dir,
   1096                sink=self._GetCacheSink(),
-> 1097                dataset_keys=full_analyze_dataset_keys_list))
   1098 
   1099         if compute_statistics or materialization_format is not None:

~/anaconda3/envs/tf2/lib/python3.6/site-packages/apache_beam/transforms/ptransform.py in __ror__(self, pvalueish, _unused)
    995 
    996   def __ror__(self, pvalueish, _unused=None):
--> 997     return self.transform.__ror__(pvalueish, self.label)
    998 
    999   def expand(self, pvalue):

~/anaconda3/envs/tf2/lib/python3.6/site-packages/apache_beam/transforms/ptransform.py in __ror__(self, left, label)
    559     pvalueish = _SetInputPValues().visit(pvalueish, replacements)
    560     self.pipeline = p
--> 561     result = p.apply(self, pvalueish, label)
    562     if deferred:
    563       return result

~/anaconda3/envs/tf2/lib/python3.6/site-packages/apache_beam/pipeline.py in apply(self, transform, pvalueish, label)
    619       try:
    620         old_label, transform.label = transform.label, label
--> 621         return self.apply(transform, pvalueish)
    622       finally:
    623         transform.label = old_label

~/anaconda3/envs/tf2/lib/python3.6/site-packages/apache_beam/pipeline.py in apply(self, transform, pvalueish, label)
    627     # every child transform in a composite.
    628     if self._current_transform() is self._root_transform():
--> 629       alter_label_if_ipython(transform, pvalueish)
    630 
    631     full_label = '/'.join(

~/anaconda3/envs/tf2/lib/python3.6/site-packages/apache_beam/utils/interactive_utils.py in alter_label_if_ipython(transform, pvalueish)
     73     from IPython import get_ipython
     74     prompt = get_ipython().execution_count
---> 75     pipeline = _extract_pipeline_of_pvalueish(pvalueish)
     76     if (pipeline
     77         # We only alter for transforms to be applied to user-defined pipelines

~/anaconda3/envs/tf2/lib/python3.6/site-packages/apache_beam/utils/interactive_utils.py in _extract_pipeline_of_pvalueish(pvalueish)
     86     pvalue = pvalueish[0]
     87   elif isinstance(pvalueish, dict):
---> 88     pvalue = next(iter(pvalueish.values()))
     89   else:
     90     pvalue = pvalueish

StopIteration: 
```
This error goes way if you just apply vocab, you don't even have to use that variable i.e.
``` python
def preprocessing_fn(inputs):
    outputs = {}
    integerized_label = tft.compute_and_apply_vocabulary(inputs[LABEL_KEY],vocab_filename="labels.txt")
    for key in TEXT_FEATURES.keys():
        outputs[transformed_name(key)] = inputs[key]
    return outputs
```
Is this expected?

**Comment by zoyahav** [comment]
Yes, this is a known issue with TFX 0.24, see the following comment for a workaround, as well as the last comment regarding using TFX nightly:
https://github.com/tensorflow/tfx/issues/2668#issuecomment-712662548

**Comment by albertnanda** [comment]
Thanks for your help. Closing this issue.
