### ISSUE TITLE
Error when using TF2 hub modules (Universal Sentence Encoder v.5 and Bert)

### ISSUE THREAD

**Issue by hyeonsuukang** [tensorflow/transform#208]
* I'm getting an error running the following code in direct runner. 
This error is related to https://github.com/tensorflow/transform/issues/160, in which I followed @varshaan 's lead and used the transform v.0.25.0 and with force_tf_compat_v1 = False when using TF2 Hub modules.

* When I try using Universal Sentence Encoder v.5, I get the following error message (for the complete log, see universal-sentence-encoder-large.logs):

`ValueError: Tensor EncoderDNN/DNN/ResidualHidden_0/dense/kernel is not found in b'/var/folders/lz/gsnkwy_s7_v_vhq14pytkvxm0000gp/T/tmpst5gqvn_/tftransform_tmp/d0c83feb27f2416ba3072c80f11f09c6/variables/variables' checkpoint {'save_counter': [], 'EncoderTransformer/hidden_layers/tanh_layer_0/dense/kernel/part_9': [34, 512], 'EncoderTransformer/hidden_layers/tanh_layer_0/dense/kernel/part_26': [34, 512], ... [while running 'Extract embeddings/AnalyzeDataset/ComputeDeferredMetadata[compat_v1=True]']`

* For Bert, I get 
```
RuntimeError: tensorflow_transform.graph_tools._UnexpectedTableError: An unexpected initializable table was encountered (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_/tmp/tmp1fa1fysc/38d2822a4c0f9e7fab4a1a72942ed2a45d9b3976/vocab.txt_-2_-1_load_5_357"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: true
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
experimental_debug_info {
  original_node_names: "hash_table"
}
) [while running 'Extract embeddings/TransformDataset/Transform']
```

Any help would be appreciated!

* Steps of reproduction.
1. Clone the following repo and index into the root of the folder: https://github.com/hyeonsuukang/tf-transform-error-reporduction
2. Create a virtual environment: `$virtualenv -p python3.7 env3.7`
3. Install dependencies (see the version info below) : `$pip install -r requirements.txt`
4. Run the script:
```
$chmod a+x ./run_pipeline.sh
$./run_pipeline.sh
```
5. Comment/uncomment the MODEL_URL declaration in modules/pipeline.py to test different models
6. Error logs are in the following files:
- For Universal Sentence Encoder v.5 (https://tfhub.dev/google/universal-sentence-encoder-large/5), see universal-sentence-encoder-large.logs
- For Expert Bert trained on PubMed (https://tfhub.dev/google/experts/bert/pubmed/2), see bert-pubmed.logs

* Dependencies and package version info:
```
numpy==1.18.5
absl-py==0.10.0
apache-beam[gcp]
tensorflow>=2.0.0
tensorflow-hub
tfx-bsl
tensorflow-transform==0.25.0
tensorflow-text

```

**Comment by varshaan** [comment]
Thanks for the detailed explanation. This log: "ComputeDeferredMetadata[**compat_v1=True**]" makes me think your pipeline is still using the tf.compat.v1 path. From your code, you seem to be setting force_tf_compat_v1 in [1]. `embed_text` from what I can see is only called within the preprocessing_fn and hence never invoked before the tft API calls. My guess is that force_tf_compat_v1 stays True within the tft_beam.Context context. Could you either force this to be False, or add a log statement here [2] to verify?

The other possibility is that you have an explicit call to disable TF2 somewhere, but I don't see this in your repro, so I think that is less likely.

Let me know if you still see an issue after verifying that force_tf_compat_v1 is actually set to False.

[1] https://github.com/hyeonsuukang/tf-transform-error-reporduction/blob/master/modules/pipeline.py#L43
[2] https://github.com/hyeonsuukang/tf-transform-error-reporduction/blob/master/modules/pipeline.py#L82

**Comment by hyeonsuukang** [comment]
Ah, thanks for catching the mistake!

**Comment by hyeonsuukang** [comment]
Ah, thanks for catching the mistake!

Fixed the code and verified the value of force_tf_compat_v1 as False when using Universal Sentence Encoder v.5
https://github.com/hyeonsuukang/tf-transform-error-reporduction/commit/17d0ce2ba3f03f5b85f72b00f4d7dcb3a2ff090e

Now I'm seeing the following. Strange. Any thoughts?

```
AttributeError: in user code:

    /Users/hyeonsuk/Desktop/Projects/deep_search_backend/tf_hub_transform_minimal/env3.7/lib/python3.7/site-packages/tensorflow_transform/schema_inference.py:590 metadata_fn  *
        reversed_features = _get_tensor_value_to_key_map(transformed_features)
    /Users/hyeonsuk/Desktop/Projects/deep_search_backend/tf_hub_transform_minimal/env3.7/lib/python3.7/site-packages/tensorflow_transform/schema_inference.py:489 _get_tensor_value_to_key_map  *
        result[values.name] = key

    AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by hyeonsuukang** [comment]
Ah, thanks for catching the mistake!

Fixed the code and verified the value of force_tf_compat_v1 as False when using Universal Sentence Encoder v.5
https://github.com/hyeonsuukang/tf-transform-error-reporduction/commit/17d0ce2ba3f03f5b85f72b00f4d7dcb3a2ff090e

I see the following assertion error about untracked object Tensor. Any thoughts?
See `universal-sentence-encoder-large-forced-compat-v1.logs` for the full log.

```
AssertionError: Tried to export a function which references untracked object Tensor("112358:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. [while running 'Extract embeddings/AnalyzeDataset/CreateSavedModel/CreateSavedModel']```

**Comment by varshaan** [comment]
Hi, I tried repro-ing your error message and the USE v5 works fine for me. I do see a different error(`AttributeError: 'dict' object has no attribute 'name'`) with the BERT model though that I am looking into. One possibility is that with force_tf_compat_v1=False, the preprocessing_fn is traced using tf.function and autograph. So the fact that you have a bunch of if-else conditions on picking the model may mean that ops from the TF1 model are getting added to the graph (though not being used). For sanity, could you try changing your embed_text method to only load and apply the USE v5 model? Thanks!

**Comment by hyeonsuukang** [comment]
Hi, 

Thanks for the update.
I've cleaned up `pipeline.py` (https://github.com/hyeonsuukang/tf-transform-error-reporduction/blob/USE-only/modules/pipeline.py), created a new python3.7 virtual environment, and tried running the code again. I decided to start with a clean slate because I noticed that sometimes the `saved_model` in the tfhub_modules folder gives an OSError. I'm guessing conflicts can happen if I concurrently use two different versions of the same hub module (e.g., universal sentence encoder).

`OSError: SavedModel file does not exist at: /var/folders/lz/gsnkwy_s7_v_vhq14pytkvxm0000gp/T/tfhub_modules/c9fe785512ca4a1b179831acb18a0c6bfba603dd/{saved_model.pbtxt|saved_model.pb}
`

But even after starting in a new python3.7 environment (with `tensorflow-transform==0.25.0`) I'm still getting the assertion error like the following (see https://github.com/hyeonsuukang/tf-transform-error-reporduction/blob/USE-only/universal-sentence-encoder-large-v5.logs for a full error log).
Do you mind sharing the versions of packages you used for running the code without an error? Esp. versions for tensorflow, apache-beam[gcp] tensorflow-hub, and tensorflow-transform would be helpful-- Thanks so much!

`AssertionError: Tried to export a function which references untracked object Tensor("112361:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. [while running 'Extract embeddings/AnalyzeDataset/CreateSavedModel/CreateSavedModel']`

**Comment by varshaan** [comment]
Hi,

Sorry for the delay, but I managed to raise the AssertionError that you are seeing. Could you modify your embed_text method to simply load and apply the hub module and not save it to a global variable? 

As for versions, I was running Transform 0.25 with TF 2.3 and TF Hub 0.10.

```
import tensorflow_hub as hub

def embed_text(text):
    model = hub.load(MODEL_URL)
    return model(text)
```

Let me know if this works. Thanks!

**Comment by arghyaganguly** [comment]
@hyeonsuukang, please reply on the above comment from  @varshaan and confirm if this issue can be closed.Thanks.

**Comment by hyeonsuukang** [comment]
Issue resolved, thanks!

**Comment by arghyaganguly** [comment]
Closing this based on the previous comment by @hyeonsuukang.Thanks.
