### ISSUE TITLE
Support Secrets for Kubeflow serialized components

### ISSUE THREAD

**Issue by vaskozl** [tensorflow/transform#226]
I currently have a presto_example_gen like component for reading from an SQL database which takes database credentials.

https://github.com/tensorflow/tfx/blob/5f78c24d067f81b991452f62b7cab791950e06fc/tfx/examples/custom_components/presto_example_gen/presto_component/executor.py#L123

Since the `kubeflow_dag_runner` serializes the components the password is available in plain text in Kubeflow even if I were to add it through the CI instead of committing it to the pipeline code.

While there is support to mount secrets as env variables through operator functions, I don't think there is a way to use variables in the TFX container. Would be great to be able to support substituting in secrets when de-serializing, or if there is already a way, add an example.

**Comment by zoyahav** [comment]
@arghyaganguly could you please move this issue to the TFX repo?
