### ISSUE TITLE
how could I filter the logs from apache_beam.runner?

### ISSUE THREAD

**Issue by xexiyong** [tensorflow/transform#229]
Hi, When I import the tft_beam, the following logs rushing on the console:

DEBUG:apache_beam.runners.worker.bundle_processor:start <DataInputOperation WriteTransformFn/CreateSole/Impulse receivers=[SingletonConsumerSet[WriteTransformFn/CreateSole/Impulse.out0, coder=WindowedValueCoder[BytesCoder], len(consumers)=1]]>
DEBUG:apache_beam.runners.worker.bundle_processor:finish <DataInputOperation WriteTransformFn/CreateSole/Impulse receivers=[SingletonConsumerSet[WriteTransformFn/CreateSole/Impulse.out0, coder=WindowedValueCoder[BytesCoder], len(consumers)=1]]>

Is anyway exists filtering these logs?

**Comment by arghyaganguly** [comment]
Please provide a code snippet to reproduce the issue.I have tried with

**Comment by zoyahav** [comment]
I believe this question may be more appropriate on the apache_beam repo?
