### ISSUE TITLE
string_to_int() got an unexpected keyword argument 'vocab_filename'

### ISSUE THREAD

**Issue by jcomfort4** [tensorflow/transform#23]
I am trying to use tft.string_to_int() with a vocab_filename, but when I ran this I got an error 

TypeError: string_to_int() got an unexpected keyword argument 'vocab_filename'. However, the mappers.py function shown here clearly has vocab_filename listed as an argument. Is this vocab_filename no longer supported?

My vocab filename is a .txt file with each vocab word on a newline and I was hoping that this would be usable to create the string_to_int function on the fly.  Is there some step that I am missing?

**Comment by zoyahav** [comment]
Note that vocab_filename was added to tf.transform in out last update on 8/5:
https://github.com/tensorflow/transform/pull/22

This is not yet part of a release, so you would need to use the version at head to be able to use it or wait for the next release.
Also keep in mind that the version at head is tested with tensorflow nightly versions, so you may need to update that package as well.

**Comment by jcomfort4** [comment]
@zoyahav Thanks! That makes sense -- any expectation of when the next release would be?

**Comment by KesterTong** [comment]
We do releases about once a month, but the next release may be delayed so 1-2 months.

**Comment by KesterTong** [comment]
actually I was mistaken about the delay, next release will be ~1 month
