### ISSUE TITLE
Add support for pyarrow>=3.0.0 or use pyarrow.binary instead of pyarrow.large_binary for string types

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#232]
@zoyahav cc @rcrowe-google 

(Not sure if I should make this issue here or in tfx-bsl. This project seems to respond to issues faster)

With the release of TFT 0.29.0 and the addition of the `output_record_batches` flag, the Transform step has become significantly more efficient. We can now take the `RecordBatch` output and pass it directly into `tfx_bsl.coders.example_coder.RecordBatchToExamples` before writing to TFRecords. In my experiments, this saves around 35% of dataflow vCPU-hours for some real-world `AnalyzeAndTransformDataset` test cases, so this is quite a nontrivial improvement!

However, we would like to support output data formats other than TFRecords, such as Parquet. Unfortunately, when we set `output_record_batches` to true it encodes string features as `pyarrow.LargeBinaryType` instead of `pyarrow.BinaryType` (this is due to [`tfx-bsl`](https://github.com/tensorflow/tfx-bsl/blob/8d48ef4cc19b42707465f5ab62f4a907828309c1/tfx_bsl/tfxio/tensor_to_arrow.py#L493)). For `pyarrow==2.0.0`, `pyarrow.parquet` does not seem to support writing `LargeBinaryType` to parquet output, nor does it support casting `LargeBinaryType` to `BinaryType`. However, if you manually force installation of `pyarrow==3.0.0`, it works. So it seems that currently in order to take TFT output as RecordBatches and write to Parquet we either need to use `pyarrow==3.0.0` (which appears to be supported in `apache-beam>=2.29.0`) or `tfx-bsl` needs to change the encoding for string types to `BinaryType`.

**Comment by cyc** [comment]
Thanks for the update @iindyk. I can confirm that `pyarrow==3.0.0` seems to work in my fairly limited use case, but I imagine more substantial testing needs to be completed. The bigger issue is that apache-beam, tfx-bsl, tensorflow_data_validation, etc. all require `pyarrow>=1,<3` so in order to unblock this issue we need to wait for all the other packages to update to 3.0.0.

**Comment by iindyk** [comment]
apache-beam seems to be [allowing it](https://github.com/apache/beam/blob/b5a8b543724ece659c7f3b195a891b7088dd5b1f/sdks/python/setup.py#L153)
@brills may have an update on plans for `pyarrow==3.0.0` support in tfx-bsl and tfdv

**Comment by brills** [comment]
update- We may be able to upgrade to pyarrow 4.0 soon.

**Comment by cyc** [comment]
@brills awesome! Is there a specific release number you are targeting for the pyarrow upgrade?

**Comment by JoshLipschultz** [comment]
> The bigger issue is that apache-beam, tfx-bsl, tensorflow_data_validation, etc. all require `pyarrow>=1,<3` so in order to unblock this issue we need to wait for all the other packages to update to 3.0.0.

By the way, `apache-beam` is now on 4.0.1, and soon to be 5.0.0 (with no changes, I think, based on https://github.com/apache/beam/pull/15359)
