### ISSUE TITLE
`ModuleNotFoundError`: 1.4.0 (and below, possibly) missing an explicit `future` dependency

### ISSUE THREAD

**Issue by IanTayler** [tensorflow/transform#257]
As of right now, new installations of `tensorflow-transform==1.4.0` fail to import with a `ModuleNotFoundError` because the `future` library is not marked as a dependency in the setup.py.

This likely wasn't a problem before because some recursive dependency of tft depended on `future`, masking the issue. But `future` _is_ a hard dependency of tft 1.4.0, as it is imported on `import tensorflow_transform`, so it should probably be added as a dep in a `1.4.1` release (assuming this team does back-releases of that kind).

For people looking for a hotfix in your own project, adding `future` as a dependency of your project should be enough.

This isn't a problem in 1.5.0 because the only usage of `future` was removed [in this commit](https://github.com/tensorflow/transform/commit/e5e0560e092b3ba66138f2250cc31716c5405081).

**Comment by davidxia** [comment]
My team's using `tfx==1.3.4` and also hit this today. This tfx version pulls in `tensorflow-transform==1.3.0` which explicitly [depends on `future` here](https://github.com/tensorflow/transform/blob/v1.3.0/tensorflow_transform/analyzer_nodes.py) but doesn't declare it as a dependency.

We worked around by adding `future==0.18.2` to our own `requirements.txt`.

**Comment by jeongukjae** [comment]
Same here. I'm using `tensorflow-transform==1.4.0` and `tfx==1.4.1`, and `ModuleNotFoundError: No module named 'future'` raised.
After the `pip install future`, it works.

**Comment by jiyongjung0** [comment]
FYI, `tensorflow-transform` 1.4.1 was released with `future` as an additional dependency.

**Comment by davidxia** [comment]
This issue can be closed since https://github.com/tensorflow/transform/pull/262 is merged.

**Comment by davidxia** [comment]
Actually I noticed the `future` requirement wasn't added to the [1.5.0](https://github.com/tensorflow/transform/blob/v1.5.0/setup.py) or [1.6.0](https://github.com/tensorflow/transform/blob/v1.6.0/setup.py) branches. Any chance they can be updated as well?

**Comment by zoyahav** [comment]
This shouldn't be needed as the dependency on future was removed in 1.5, did you run into an issue with 1.5 or 1.6?

See 1.4.1 https://github.com/tensorflow/transform/blob/8a63bc9eabd156e2cbcab2c6db9dc0a2c8a27537/tensorflow_transform/analyzer_nodes.py#L31
v.s. 1.5 https://github.com/tensorflow/transform/blob/fe97b4ba701f1fcef6fe28c9d43468ac73b42ed5/tensorflow_transform/analyzer_nodes.py#L31

**Comment by zoyahav** [comment]
Thanks for verifying!
