### ISSUE TITLE
Unable to get the size of vocabulary before apply_vocabulary

### ISSUE THREAD

**Issue by ynait** [tensorflow/transform#261]
I am using tft in TFX and needs to transform string list class labels into multi-hot indicators inside `preprocesing_fn`. Essentially:
```
vocab = tft.vocabulary(inputs['label'])
outputs['label'] = tf.cast(
    tf.sparse.to_indicator(
       tft.apply_vocabulary(inputs['label'], vocab),
       vocab_size=VOCAB_SIZE,
    ),
    "int64",
)
```
I am trying to get `VOCAB_SIZE` from the result of `vocab`, but couldn't find a way to satisfy the deferred execution and known shapes. The closest I got below wouldn't pass the saved model export as the shape for label is unknown.
```
def _make_table_initializer(filename_tensor):
    return tf.lookup.TextFileInitializer(
        filename=filename_tensor,
        key_dtype=tf.string,
        key_index=tf.lookup.TextFileIndex.WHOLE_LINE,
        value_dtype=tf.int64,
        value_index=tf.lookup.TextFileIndex.LINE_NUMBER,
    )

def _vocab_size(deferred_vocab_filename_tensor):
    initializer = _make_table_initializer(deferred_vocab_filename_tensor)
    table = tf.lookup.StaticHashTable(initializer, default_value=-1)
    table_size = table.size()
    return table_size

deferred_vocab_and_filename = tft.vocabulary(inputs['label'])
vocab_applied = tft.apply_vocabulary(inputs['label'], deferred_vocab_and_filename)
vocab_size = _vocab_size(deferred_vocab_and_filename)
outputs['label'] = tf.cast(
    tf.sparse.to_indicator(vocab_applied, vocab_size=vocab_size),
    "int64",
)
```
Got
```
ValueError: Feature label (Tensor("Identity_3:0", shape=(None, None), dtype=int64)) had invalid shape (None, None) for FixedLenFeature: apart from the batch dimension, all dimensions must have known size [while running 'Analyze/CreateSavedModel[tf_v2_only]/CreateSavedModel']
```

Any idea how to achieve this?

**Comment by cyc** [comment]
Why do you need to convert it to multi-hot inside of preprocessing_fn? Could it be done after the transformation step?

**Comment by ynait** [comment]
Label binarization to multi-hot is needed to wire it up as a multi-label classification in keras. Since I am using a Transform component, getting everything done here saves these steps at training time.

**Comment by varshaan** [comment]
tft.experimental.get_vocabulary_size_by_name [1] was added in TFT 1.6 for this purpose. The census example [2] has an example use case of the API. 

[1] https://www.tensorflow.org/tfx/transform/api_docs/python/tft/experimental/get_vocabulary_size_by_name
[2] https://github.com/tensorflow/transform/blob/master/examples/census_example_common.py#L145

**Comment by ynait** [comment]
Thank you for creating that new API. Marking as resolved.

**Comment by ynait** [comment]
I found out the `get_num_buckets_for_transformed_feature` API provides the same functionality. Is my understanding right?
https://www.tensorflow.org/tfx/transform/api_docs/python/tft/get_num_buckets_for_transformed_feature

**Comment by varshaan** [comment]
If you only computed vocabulary (using `tft.vocabulary`) in transform, but didn't apply it (using `tft.apply_vocabulary/tft.compute_and_apply_vocabulary`), you don't have access to this information through `get_num_buckets_for_transformed_feature`.
