### ISSUE TITLE
Release new version that's compatible with `tfx[kfp]==1.10.0`

### ISSUE THREAD

**Issue by davidxia** [tensorflow/transform#288]
Currently master branch has `Depends on tensorflow>=1.15.5,<2 or tensorflow>=2.10,<2.11` from [this commit](https://github.com/tensorflow/transform/commit/1b2d9b6eda4bbccd3587bbe5080f69ac0363c397#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R53). But this isn't released yet.

Here's a minimal repro of the dependency conflicts with `tfx[kfp]==1.10.0`.

```
❯ cat requirements.in
tfx[kfp]==1.10.0
tensorflow-ranking

❯ pip-compile requirements.in
Could not find a version that matches tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<2.10,<3,>=1.15.5,>=2.10.0 (from tfx[kfp]==1.10.0->-r requirements.in (line 1))
Tried: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0, 2.9.1, 2.9.2, 2.10.0
Skipped pre-versions: 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.7.0rc0, 2.7.0rc1, 2.8.0rc0, 2.8.0rc1, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.11.0rc0, 2.11.0rc1
There are incompatible versions in the resolved dependencies:
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<3,>=1.15.5 (from tfx-bsl==1.10.1->tfx[kfp]==1.10.0->-r requirements.in (line 1))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<3,>=1.15.5 (from tensorflow-model-analysis==0.41.1->tfx[kfp]==1.10.0->-r requirements.in (line 1))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<2.10,>=1.15.5 (from tfx[kfp]==1.10.0->-r requirements.in (line 1))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<2.10,>=1.15.5 (from tensorflow-transform==1.10.1->tfx[kfp]==1.10.0->-r requirements.in (line 1))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<3,>=1.15.5 (from tensorflow-data-validation==1.10.0->tfx[kfp]==1.10.0->-r requirements.in (line 1))
  tensorflow<3,>=2.10.0 (from tensorflow-serving-api==2.10.0->tfx[kfp]==1.10.0->-r requirements.in (line 1))
```

Any rough timeline of when this will be released? Thanks!

**Comment by singhniraj08** [comment]
@davidxia,

What version of Transform you are using? Can you please try with latest release [1.10.1 ](https://github.com/tensorflow/transform/releases/tag/v1.10.1)and see if the dependency conflicts are resolved. 
TFX latest release 1.10.0 supports Transform version 1.10.1. Please find dependency updates in [TFX 1.10.0 release note](https://github.com/tensorflow/tfx/releases/tag/v1.10.0).

Thank you!

**Comment by singhniraj08** [comment]
@davidxia,

I tried installing `tensorflow_transform nightly version `and the dependency conflict still occurs with `tensorflow 2.10`. 

When we pip install `tensorflow_transform`, it automatically installs `tensorflow 2.9.2`. While the team works on this issue, the workaround is to use `tensorflow 2.9.2` with `tensorflow_transform 1.10.1`. 

Thank you!

**Comment by rcrowe-google** [comment]
Adding @1025KB
Please keep in mind that the master branch is work in progress, and is not guaranteed to work with the released version.

**Comment by singhniraj08** [comment]
@davidxia,

TFT 1.10 supports only TF 1.15.5 / 2.9. See: [Transform compatible versions table](https://github.com/tensorflow/transform#compatible-versions)
In order to use a later TF version, users can now either install tensorflow-transform 1.11.0, or [nightly](https://github.com/tensorflow/transform#nightly-packages).

Thank you!

**Comment by davidxia** [comment]
The pip-compile error I had above was actually incorrect behavior from legacy pip-compile resolver logic. `pip-compile` ≥ 6.10.0 with `--resolver backtracking` successfully resolves the dependencies.

> The legacy resolver will occasionally fail to resolve dependencies. The backtracking resolver is more robust, but can take longer to run in general.

— https://pypi.org/project/pip-tools/
