### ISSUE TITLE
Apple Silicon support for tensorflow-transform not available as tfx-bsl does not support it?

### ISSUE THREAD

**Issue by oonisim** [tensorflow/transform#298]
As in [Any plans to support Apple silicon devices like M1 Macs? #48](https://github.com/tensorflow/tfx-bsl/issues/48), tfx-bsl has the issue open for Apple Silicon.

Does this mean tensorflow transform does not work on Apple Silicon?

**Comment by gaikwadrahul8** [comment]
Hi, @oonisim 

Apologize for the delayed response and As far as I know TFX and it's supported libraries like `tensorflow-transform` does not support for Apple Mac M1 and M2 at the moment and We are currently working on Apple Mac M1, M2 support, and will have an update in the fairly near future. In the meantime, Other option include using a VM. We understand that option is not ideal.

We don’t have a firm ETA yet. As similar issues are already being tracked [#1864 ](https://github.com/tensorflow/serving/issues/1816), [#48](https://github.com/tensorflow/tfx-bsl/issues/48)  and [TF Forum thread](https://discuss.tensorflow.org/t/i-want-to-use-the-tfx-1-6-1-on-mac-m1-max/8110) so I would request you to please follow the same issues or TF-Forum thread to get latest updates on this issue and close this issue.

Thank you!

**Comment by oonisim** [comment]
@gaikwadrahul8 , thanks for the update. Appreciate it.

**Comment by Cunoo** [comment]
Thanks ! i'll just leave comment here
