### ISSUE TITLE
Raise pyarrow upper bound?

### ISSUE THREAD

**Issue by sid-kap** [tensorflow/transform#299]
Would it be possible to remove the pyarrow upper bound in the next release?

The current release of TFT pins pyarrow to an 18-month old version (6.0.0; the latest is 11.0.0).

**Comment by singhniraj08** [comment]
@zoyahav,

Can we remove the pyarrow upper bound dependency or update pyarrow dependency to latest release(11.0.0). Thanks!

**Comment by AnandInguva** [comment]
+1 to it.

**Comment by zoyahav** [comment]
pyarrow dependency relies on the tfx-bsl pyarrow dependency. We'll have to look into updating both.

**Comment by iindyk** [comment]
tfx-bsl packages arrows c++ build. the build version and pyarrow dependency must be compatible. The latter is sometimes possible outside of major version boundaries, but needs extensive testing, so we'll likely keep a single major pyarrow version dependency. Are there some specific APIs you're after that are not available in older pyarrow?

**Comment by sid-kap** [comment]
@zoyahav @iindyk Thanks for looking into this!

I'd like to upgrade pyarrow in my venv for a few reasons:
* pyarrow.Table.join is only available in >=7
* The latest version of polars requires >= 7
* pandas 2.0 requires >= 7
* huggingface/datasets requires >= 8

**Comment by iindyk** [comment]
We could only reliably do pyarrow 10 due to testing env coverage. I think `apache_beam` has '<10.0.0' [for the latest released](https://github.com/apache/beam/blob/0938c0ffce64565b6f186f081e00bd6ad1d128ec/sdks/python/setup.py#L143) but it should be bumped to '<12.0.0' in [2.47 ](https://github.com/apache/beam/blob/4bca1d13fd2f474701f307da5877161e1eb08dc0/sdks/python/setup.py#L144). So we'll have to wait for the latest beam release, update to the latest beam and only then update pyarrow.

**Comment by sid-kap** [comment]
That would be great, thanks!!

**Comment by sid-kap** [comment]
It looks like beam 2.47 and 2.48, which raise the bound to <12.0.0, are now released.
Does that mean we can bump pyarrow on the next tft release? Any idea when the next release is planned for?

**Comment by iindyk** [comment]
We'd need to raise our minimal required beam version for that which has to be coordinated with other TFX libs. @rtg0795 is there a plan to do this in one of the next releases?

**Comment by rtg0795** [comment]
Hi @iindyk , 
Didn't hear anything of that. Will followup on this and update you soon.

**Comment by iindyk** [comment]
upd: we bumped the pyarrow version to >=10,<11 in https://github.com/tensorflow/transform/commit/1317ecda78f23b4fea1facb16cd881c072ae8dad, the next release will have the updated requirement

**Comment by sid-kap** [comment]
Thank you!!
