### ISSUE TITLE
[Assistir／TV] Croácia x Portugal AO VIVO 𝗢𝗡𝗟𝗜𝗡𝗘 𝗚𝗿𝗮𝘁𝗶𝘀 𝟭𝟴 𝗡𝗼𝘃𝗲𝗺𝗯𝗲𝗿 𝟮𝟬𝟮𝟰

### ISSUE THREAD

**Issue by xaviko9323** [tensorflow/transform#328]
Croácia e Portugal se enfrentam nesta segunda-feira (18), a partir das 16h45 (de Brasília), no Estádio Poljud, pela sexta rodada da Liga das ...
O jogo entre Croácia e Portugal nesta segunda-feira (18), às 16h45 (de Brasília), será transmitido ao vivo no SporTV (TV fechada). Palpites para ...

Croácia está enfrentando Portugal começando em 18 de nov. de 2024 às 19:45 UTC no Stadion Poljud estadio, Split cidade, Croatia. A partida faz parte do UEFA Nations League, League A, Gr. 1.

Ｃｒｏáｃｉａ ｅｎｆｒｅｎｔｏｕ Ｐｏｒｔｕｇａｌ ｅｍ １ ｐａｒｔｉｄａｓ ｎｅｓｔａ ｔｅｍｐｏｒａｄａ． Ｎｅｓｔｅ ｍｏｍｅｎｔｏ， Ｃｒｏáｃｉａ ｅｓｔá ｎａ ２º ｐｏｓｉçãｏ， ｅ Ｐｏｒｔｕｇａｌ ｅｓｔá ｎａ １º ｐｏｓｉçãｏ． Ｇｏｓｔａｒｉａ ｄｅ ｃｏｍｐａｒａｒ ｏ（ａ） ｊｏｇａｄｏｒ（ａ） ｍｅｌｈｏｒ ａｖａｌｉａｄｏ（ａ） ｅｍ ａｍｂａｓ ａｓ ｅｑｕｉｐｅｓ？ Ｏ Ｓｏｆａｓｃｏｒｅ ａｖａｌｉａ ｃａｄａ ｊｏｇａｄｏｒ（ａ） ｂａｓｅａｄｏ ｅｍ ｖáｒｉｏｓ ｆａｔｏｒｅｓ．
Ｎｏ ｐｌａｃａｒ ａｏ ｖｉｖｏ Ｓｏｆａｓｃｏｒｅ ｖｏｃê ｅｎｃｏｎｔｒａ ｔｏｄｏｓ ｏｓ ｒｅｓｕｌｔａｄｏｓ ａｎｔｅｒｉｏｒｅｓ ｄａｓ ｐａｒｔｉｄａｓ ｅｎｔｒｅ Ｃｒｏáｃｉａ ｅ Ｐｏｒｔｕｇａｌ ｏｒｄｅｎａｄｏｓ ｐｏｒ ｓｅｕｓ ｃｏｎｆｒｏｎｔｏｓ ｄｉｒｅｔｏｓ． Ｓｏｆａｓｃｏｒｅ ｔａｍｂéｍ ｏｆｅｒｅｃｅ ａ ｍｅｌｈｏｒ ｍａｎｅｉｒａ ｄｅ ａｃｏｍｐａｎｈａｒ ｏ ｐｌａｃａｒ ａｏ ｖｉｖｏ ｄｅｓｔａ ｐａｒｔｉｄａ ｃｏｍ ｖáｒｉｏｓ ｄｅｔａｌｈｅｓ ｅｓｐｏｒｔｉｖｏｓ． Ａｓｓｉｍ， ｖｏｃê ｐｏｄｅ：

Ｄｅｓｃｕｂｒａ ｑｕｅｍ ｍａｒｃｏｕ ｅｍ ｕｍａ ｐａｒｔｉｄａ ａｏ ｖｉｖｏ

Ｏｂｔｅｎｈａ ｉｎｆｏｒｍａçõｅｓ ａｏ ｖｉｖｏ ｓｏｂｒｅ ｑｕａｌ ｔｉｍｅ ｅｓｔá ｄｏｍｉｎａｎｄｏ ａ ｐａｒｔｉｄａ ｕｓａｎｄｏ Ａｔｔａｃｋ Ｍｏｍｅｎｔｕｍ
Ｓｉｇａ ｅｓｔａｔíｓｔｉｃａｓ ｄｅｔａｌｈａｄａｓ ｔａｉｓ ｃｏｍｏ ｐｏｓｓｅ ｄｅ ｂｏｌａ， ｃｈｕｔｅｓ， ｅｓｃａｎｔｅｉｏｓ， ｃｈａｎｃｅｓ ｃｒｉａｄａｓ， ｃａｒｔõｅｓ， ｐａｓｓｅｓ ｍａｔａｄｏｒｅｓ， ｄｕｅｌｏｓ ｅ ｍａｉｓ
Ｓｉｇａ ｔｏｄａｓ ａｓ ｐａｒｔｉｄａｓ ｅｍ ｃａｓａ ｅ ｆｏｒａ ｄｅ ｃａｓａ ｄｏ（ａ） ＵＥＦＡ Ｎａｔｉｏｎｓ Ｌｅａｇｕｅ， Ｌｅａｇｕｅ Ａ， Ｇｒ． １
Ｃｏｎｆｉｒａ ｃｏｍｏ ａ ｃｏｍｕｎｉｄａｄｅ Ｓｏｆａｓｃｏｒｅ ｖｏｔａ ｎａ ｅｑｕｉｐｅ ｑｕｅ ｐｒｏｖａｖｅｌｍｅｎｔｅ ｖａｉ ｖｅｎｃｅｒ ｅｓｔａ ｐａｒｔｉｄａ．

Ｔｏｄｏｓ ｅｓｓｅｓ ｒｅｃｕｒｓｏｓ ｐｏｄｅｍ ａｊｕｄá－ｌｏ ａ ｄｅｃｉｄｉｒ ｓｏｂｒｅ ａ ｐｒｅｖｉｓãｏ ｄｅ ｊｏｇｏ ｄｅ Ｃｒｏáｃｉａ ｘ Ｐｏｒｔｕｇａｌ． Ｍｅｓｍｏ ｑｕｅ ｏ Ｓｏｆａｓｃｏｒｅ ｎãｏ ｏｆｅｒｅçａ ａｐｏｓｔａｓ ｄｉｒｅｔａｓ， ｅｌｅ ｆｏｒｎｅｃｅ ａｓ ｍｅｌｈｏｒｅｓ ｏｄｄｓ ｅ ｍｏｓｔｒａ ｑｕａｉｓ ｓｉｔｅｓ ｏｆｅｒｅｃｅｍ ａｐｏｓｔａｓ ａｏ ｖｉｖｏ． Ａｓ ｏｄｄｓ ｄｅ Ｕ－ＴＶ ａｏ ｖｉｖｏ ｐｏｄｅｍ ｓｅｒ ｖｉｓｔａｓ ｎａ ｓｅçãｏ Ｆｕｔｅｂｏｌ ｐｌａｃａｒ ａｏ ｖｉｖｏ ｄｏ Ｓｏｆａｓｃｏｒｅ．

Ｏｎｄｅ ａｓｓｉｓｔｉｒ Ｃｒｏáｃｉａ ｘ Ｐｏｒｔｕｇａｌ？ Ｎａ ｓｅçãｏ Ｃａｎａｉｓ ｄｅ ＴＶ ｖｏｃê ｅｎｃｏｎｔｒａ ａ ｌｉｓｔａ ｄｅ ｔｏｄｏｓ ｏｓ ｃａｎａｉｓ ｑｕｅ ｔｒａｎｓｍｉｔｉｒãｏ ａ ｐａｒｔｉｄａ ｅｎｔｒｅ Ｃｒｏáｃｉａ ｅ Ｐｏｒｔｕｇａｌ ａｏ ｖｉｖｏ． Ｖｏｃê ｔａｍｂéｍ ｐｏｄｅ ｖｅｒ ｏ ｓｔｒｅａｍ ｄｅｓｔａ ｐａｒｔｉｄａ ａｏ ｖｉｖｏ ａｔｒａｖéｓ ｄｏｓ ｎｏｓｓｏｓ ｐａｒｃｅｉｒｏｓ ｑｕｅ ｏｆｅｒｅｃｅｍ ａｐｏｓｔａｓ， ｏｕ ｃｌｉｃａｒ ｅｍ ｑｕａｌｑｕｅｒ ｌｉｎｋ ｎｏ Ｓｏｆａｓｃｏｒｅ ｐａｒａ ｏｂｔｅｒ ｕｍ ｓｔｒｅａｍ ａｏ ｖｉｖｏ ｌｅｇａｌｉｚａｄｏ．

Ｄｅｔａｌｈｅｓ ｄｏ ｅｖｅｎｔｏ：

ＮＯＭＥ： Ｃｒｏａｔｉａ － Ｐｏｒｔｕｇａｌ
ＤＡＴＡ： １８ ｄｅ ｎｏｖ． ｄｅ ２０２４
ＨＯＲＡ： １９：４５ ＵＴＣ
ＥＳＴÁＤＩＯ： Ｓｔａｄｉｏｎ Ｐｏｌｊｕｄ， Ｓｐｌｉｔ， Ｃｒｏａｔｉａ

**Comment by vuterbasko** [comment]
cxvdf
