### ISSUE TITLE
string_to_index_table_from_tensor to be deprecated warning

### ISSUE THREAD

**Issue by jcomfort4** [tensorflow/transform#34]
WARNING:tensorflow:From /Users/user/anaconda/lib/python2.7/site-packages/tensorflow_transform/mappers.py:305: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`

I am getting this warning after a pip install, but I don't see the deprecated function being used in the source code. Is the pip install out of date?

**Comment by katsiapis** [comment]
Do you see this issue with tensorflow-transform 0.3 as well?

Either way, we plan to erase all deprecated table related code (even from our tests) as part of tensorflow-transform 0.4

**Comment by jcomfort4** [comment]
Where would I get tensorflow-transform 0.3 from? I have just been using `pip install tensorflow-transform` which results in tft 0.1.10 as that is what is supposed to be compatible with GCMLE.

**Comment by elmer-garduno** [comment]
If not on a clean environment please do `pip install --upgrade tensorflow_tranform`

**Comment by katsiapis** [comment]
tf.transform 0.4 has been [released](https://github.com/tensorflow/transform/blob/v0.4.0/RELEASE.md) so closing this issue. Feel free to reopen if you continue to see problems.
