### ISSUE TITLE
NumPy support

### ISSUE THREAD

**Issue by carlthome** [tensorflow/transform#4]
I wonder if you've considered adding support for NumPy as a data processing framework. It would be really useful to be able to use the vast amount of preprocessing functionality already written in NumPy, run that on a dataset and get it included in the TensorFlow graph for deployment. I realize that this is a really hard task, but perhaps a subset of the most common NumPy operations could be supported at least (ndarray methods)?

**Comment by KesterTong** [comment]
This is not something we have planned, though I can see that it would be useful.  On the other hand, currently low level numpy operations have TF equivalents, while high level functions we hopefully will have a fairly complete set of alternatives.
