### ISSUE TITLE
Location of data for examples?

### ISSUE THREAD

**Issue by jbingham** [tensorflow/transform#48]
The census and sentiment examples require data files that aren't located in this git repo, and there's no documentation (at least not that I saw) about where to find them.

Should there be a test data folder? Or if the data is too big, a cloud bucket perhaps?

**Comment by elmer-garduno** [comment]
Thanks @jbingham, we'll make sure to centralize this information on an examples/readme.md file. In the meantime you can download them from:

Census

https://github.com/tensorflow/transform/blob/master/getting_started.md#downloading-the-census-dataset

Sentiment

https://github.com/tensorflow/transform/blob/master/more_examples.md#sentiment-analysis

**Comment by KesterTong** [comment]
So is there agreement that we want a separate README for both examples with just enough information to run them?  And this info should be moved from their current location in `getting_started.md` and `more_examples.md`?

I think I agree with this but let's confirm this is the plan

**Comment by jbingham** [comment]
I see: census data instructions are in getting_started and there's a link to sentiment, though to the original source rather than the tensorflow examples location (presumably to avoid breaking changes). 

I personally didn't read those other pages closely enough to notice (rtfm?), since it wasn't obvious which went with which example. I'd be more likely to find them in a README. 

Then again, maybe just stick the links inside of the python files themselves? Then anyone who wants to dive in and just run the examples can't miss the links.

**Comment by harshini-gadige** [comment]
Has the documentation been updated ? If not, what is the ETA ?

**Comment by KesterTong** [comment]
Yes this was fixed, there are clearer docs on how to run exampels
