### ISSUE TITLE
Migrate examples and documentation to TF core

### ISSUE THREAD

**Issue by amygdala** [tensorflow/transform#59]
Is there some reason these examples are still using tf.contrib.learn?
e.g. https://github.com/tensorflow/transform/blob/master/examples/census_example.py#L31

(seems like that's not going to help demystify tft for users..)

Update: similarly re: mentions of "tf.Learn" in the docs, e.g. here: https://github.com/tensorflow/transform/blob/master/getting_started.md
I think this will just confuse people.

**Comment by elmer-garduno** [comment]
Thanks @amygdala, great I'll update the issue name and we'll work on migrating the examples to TF core.

**Comment by amygdala** [comment]
oh great, thanks!

**Comment by amygdala** [comment]
Update: okay, I might just put in a PR for this instead... as I mentioned to Elmer, I did the conversion for the sentiment one for my own purposes and it would be straightforward to just do the rest of it.

**Comment by elmer-garduno** [comment]
Thanks Amy, a PR will be very welcome.

**Comment by KesterTong** [comment]
Examples are now using core
