### ISSUE TITLE
'tft.coders' usage in examples doesn't work with packaged release?

### ISSUE THREAD

**Issue by amygdala** [tensorflow/transform#60]
In trying to run the examples, I get an error accessing `tft.coders`, which I see was added to the samples 15 days ago.  I'm using the 'pip install' latest version of TFT, which is 0.6.
What version is necessary to run the examples now? (Am I missing something?)

(my dev rel opinion:  user-facing examples should sync with the publicly released packages so that the examples always work).

**Comment by zoyahav** [comment]
The examples are meant to be used with the tf.Transform version that is the most recent master branch.
Note that this repo is tagged by versions, including the examples, so you should be able to run these examples with tf.Transform version 0.6:
https://github.com/tensorflow/transform/tree/v0.6.0/examples

**Comment by amygdala** [comment]
Yeah, I belatedly realized that after I opened this issue, sorry. (I don't suppose you have a pip analog to  tf-nightly?)

**Comment by zoyahav** [comment]
No problem. TF nightly wheels can be found here:
https://ci.tensorflow.org/view/tf-nightly/job/tf-nightly-linux/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/

After choosing the right whl file, and copying the link to it, it can be installed with pip by running:
pip install --upgrade <whl_link>
