### ISSUE TITLE
support for reduce_instance_dims in quantiles

### ISSUE THREAD

**Issue by cnsgsz** [tensorflow/transform#62]
just as min, max etc in analyzer.py.

**Comment by sharifgamal** [comment]
It will not be trivial to release an implementation, but we will accept the feature request.

**Comment by KesterTong** [comment]
We are now working on this.  It is part of fixing https://github.com/tensorflow/transform/issues/110

**Comment by zoyahav** [comment]
This FR was done and released as part of tf.transform 0.14 and all versions since that one:
https://github.com/tensorflow/transform/blob/master/RELEASE.md#release-0140
