### ISSUE TITLE
apply tft.TFTransformOutput.transformed_feature_spec to tf.data

### ISSUE THREAD

**Issue by Debasish-Das-CK** [tensorflow/transform#66]
dataset = tf.contrib.data.make_batched_features_dataset(
        file_pattern=transformed_examples,
        batch_size=batch_size,
        features=tf_transform_output.transformed_feature_spec(),
        reader=tf.data.TFRecordDataset,
        shuffle=True)
tft examples uses a contrib API which is not official. Can I use the following ?

dataset = tf.data.TFRecordDataset(filenames_list)
dataset = dataset.map(_parse_proto)
dataset.map(tf_transform_output.transformed_feature_spec())

**Comment by Debasish-Das-CK** [comment]
also I guess examples need to be updated with the official API...should I push a PR ?

**Comment by ravwojdyla** [comment]
@Debasish-Das-CK `tf.contrib.data.make_batched_features_dataset` is full supported and recommended see https://www.youtube.com/watch?v=uIcqeP7MFH0.
