### ISSUE TITLE
Request: nightly/dev release

### ISSUE THREAD

**Issue by ravwojdyla** [tensorflow/transform#69]
Could we please have a nightly/dev release. FYI using git reference in pip requirements seem to fail on Dataflow runner. But overall it seems like a good idea to make it easier to try new features. What do you think?

**Comment by damienpontifex** [comment]
Agreed, would love to get the new `TFTransformOutput` which isn't in the 0.6.0 release

**Comment by ravwojdyla** [comment]
@damienpontifex the same case - to unblock myself I published https://pypi.org/project/rav-tensorflow-transform/ - feel free to use it until we get dev release here.

**Comment by damienpontifex** [comment]
@ravwojdyla I ended up just doing `python2 -m pip install -U git+git://github.com/tensorflow/transform.git@master` to get the latest.

**Comment by ravwojdyla** [comment]
@damienpontifex sounds good, initially I have done the same, but then this did not work on Dataflow runner - job just gets stuck at the very beginning - I assume it has issues installing the dependency. This goes away when I use pypi deployed package.

**Comment by zoyahav** [comment]
> python2 -m pip install -U git+git://github.com/tensorflow/transform.git@master

That's probably the best option right now, we unfortunately can't put together and maintain nightly releases at the moment.
