### ISSUE TITLE
More docs for apply_function needed?

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/transform#75]
I am implementing a conversion from from characters to a list of character indicies (int). To perform the conversion, I wrote a function `convert_character` to split the input string and perform a table lookup for every character.

The conversion function runs fine when I convert a `tf.constant('test string')` in a TF graph. The conversion will return something like `[45, 4, 18, 19, 70, 18, 19, 17, 8, 13, 6]`.

If I apply the same apply the conversion method in my TF Transform example, every character gets converted individually and the output looks like this:

```
[{u'indicies': 45},
 {u'indicies': 4},
 {u'indicies': 18},
 {u'indicies': 19},
 {u'indicies': 70},
 {u'indicies': 18},
 {u'indicies': 19},
 {u'indicies': 17},
 {u'indicies': 8},
 {u'indicies': 13},
 {u'indicies': 6}]
```

I would have expected the output to look like 

```
[{u'indicies': [45, 4, 18, 19, 70, 18, 19, 17, 8, 13, 6]},
 {u'indicies': [.....]},
]
```

Is the problem in my case the usage of `apply_function`? I noticed other users struggled with the correct use of the mapper function too (https://github.com/tensorflow/transform/issues/58). 

I also tried to replaced the `apply_function` with `tf.map_fn`, but the conversion was the same. This makes sense to me since `map_fn` is applied to every character in the string.

If anyone can point me into the right direction use `apply_function` correctly, I am happy to extend the docs to prevent similar mistakes in the future.

Here is my example character conversion code: 

```
import pprint
import tempfile
import numpy as np

import tensorflow as tf
import tensorflow_transform as tft
import tensorflow_transform.beam.impl as beam_impl
from tensorflow_transform.tf_metadata import dataset_metadata
from tensorflow_transform.tf_metadata import dataset_schema

def convert_character(input_string):
    input_characters = tf.string_split(input_string, delimiter="") 
    characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"\'?!.,:; '
    mapping_characters = tf.string_split([characters], delimiter="")
    table = tf.contrib.lookup.index_table_from_tensor(
        mapping=mapping_characters.values, default_value=0) 
    return table.lookup(input_characters.values)

def preprocessing_fn(inputs):
    """Preprocess input columns into transformed columns."""    
    return {'indicies': tft.apply_function(convert_character, inputs['sentence'])}


def main():
    
    raw_data = [
      {'sentence': 'Test string'},
      {'sentence': 'String Test'},
    ]

    raw_data_metadata = dataset_metadata.DatasetMetadata(dataset_schema.Schema({
      'sentence': dataset_schema.ColumnSchema(
          tf.string, [], dataset_schema.FixedColumnRepresentation())
    }))

    with beam_impl.Context(temp_dir=tempfile.mkdtemp()):
        transformed_dataset, transform_fn = (  # pylint: disable=unused-variable
            (raw_data, raw_data_metadata) | beam_impl.AnalyzeAndTransformDataset(
                preprocessing_fn))

        transformed_data, transformed_metadata = transformed_dataset  # pylint: disable=unused-variable

        pprint.pprint(transformed_data)

main()
```

**Comment by KesterTong** [comment]
`tft.apply_function` is now deprecated, and equivalent to just calling the function, i.e.

`tft.apply_function(convert_character, inputs['sentence'])`

is equal to

`convert_character(inputs['sentence'])`

The problem you are seeing is because you call `.values` on your `SparseTensor` which effectively flattens it by extracting just the values.  To avoid this you need to unflatten it by creating a new `SparseTensor`.  That is instead of

```
  return table.lookup(input_characters.values)
```

you need

```
  return SparseTensor(
      input_characters.indices,
      table.lookup(input_characters.values),
      input_characters.dense_shape)
```

**Comment by zoyahav** [comment]
Note that `tft.apply_function` is not longer needed (and is deprecated) starting from tf.Transform 0.9.

**Comment by harshini-gadige** [comment]
Closing this issue as it is related to tft.apply_function which is deprecated.
