### ISSUE TITLE
NaN values lead to unexpected results in scale_to_z_score

### ISSUE THREAD

**Issue by baxen** [tensorflow/transform#78]
The current implementations of mean and variance in `analyzers.py` don't seem to be able to handle NaN values. This results in the `scale_to_z_score` function giving unexpected results if the data contains any NaNs. For example:

```python
import tempfile
import tensorflow as tf
import numpy as np
import tensorflow_transform as tft
import tensorflow_transform.beam.impl as beam_impl
from tensorflow_transform.tf_metadata import dataset_metadata
from tensorflow_transform.tf_metadata import dataset_schema

size = 10000
values = np.random.normal(10.0, 10.0, size=size) # original has a mean of 10 and std of 10
values[np.random.rand(size) < 0.2] = np.nan  # but 20% are NaN

def preprocessing_fn(inputs):
    """Preprocess input columns into transformed columns."""
    x = inputs['x']
    x_zscore = tft.scale_to_z_score(x)
    return {
        'x_zscore': x_zscore,
     }

raw_data = [{'x': v} for v in values]
raw_data_metadata = dataset_metadata.DatasetMetadata(dataset_schema.Schema({
    'x': dataset_schema.ColumnSchema(
        tf.float32, [], dataset_schema.FixedColumnRepresentation())
}))

with beam_impl.Context(temp_dir=tempfile.mkdtemp()):
    transformed_dataset, transform_fn = (
        (raw_data, raw_data_metadata) | beam_impl.AnalyzeAndTransformDataset(preprocessing_fn)
    )
    transformed_data, transformed_metadata = transformed_dataset  # pylint: disable=unused-variable

transformed = np.array([d['x_zscore'] for d in transformed_data])


print(np.nanmean(transformed))  # not close to zero
print(np.nanvar(transformed))  # not close to one
```

You end up with the transformed data having a mean and variance much greater than 0 and 1 respectively. I am pretty sure this is happening because tf.reduce_sum is giving NaN for all batches that contain at least one NaN value here: https://github.com/tensorflow/transform/blob/master/tensorflow_transform/tf_utils.py#L99

I just closed a PR [#68] that fixed this in an older implementation. I'd be happy to make a PR to fix this in the current as well, I think it would be reasonable to take the mean/var of all non-NaN values and then to set any NaNs to zero as the default behavior.

**Comment by KesterTong** [comment]
Another option is to us a SparseTensor, as can be produced by a `ListColumnRepresentation`, and then use `scale_to_z_score` on the `SparseTensor`.  See the handling of `OPTIONAL_NUMERIC_FEATURE_KEYS` in https://github.com/tensorflow/transform/blob/master/examples/census_example.py.

**Comment by KesterTong** [comment]
Although if the current code already partly handles NaN values, we should probably fix it to handle them properly.  @zoyahav is the current code intended to handle NaN values?  If we were to update the handling of NaNs it would be in reduce_batch_count_mean_and_var in tf_utils.py

**Comment by zoyahav** [comment]
The current code doesn't handle NaN values in the input tensors, I'm actually not sure what the behavior should be in case of NaNs here.
Should they be seen as 0s when computing a sum? should they be counted towards the size of the tensor when computing mean?

I'm wondering if it would be better to fix this in the preprocessing_fn so that the behavior isn't surprising and matches TF ops such as reduce_sum, etc.

**Comment by baxen** [comment]
Thanks @KesterTong and @zoyahav for looking into it. Unfortunately I haven't figured out a way to do this in the preprocessing function that gives the desired result. 

You'd typically want to fill in the mean as the missing value, but I think that would require another full pass over the dataset? And even if you do that it will lower the standard deviation:

```python
import numpy as np

size = 10000
values = np.random.normal(10.0, 10.0, size=size) # original has a mean of 10 and std of 10
values[np.random.rand(size) < 0.2] = np.nan  # but 20% are NaN

# Calculate standard deviation of non-null entries
print np.nanstd(values) #~10

# Fill NaNs with the mean and then calculate standard deviation
values[np.isnan(values)] = np.nanmean(values)
print values.std()  #~9
```

I think the standard for aggregations with missing data (pandas, most SQL flavors, etc)  is to calculate the aggregation of only the non-null values. This is the same as treating them as a zero in the sum and not including them in the size of the tensor like you mentioned.

**Comment by KesterTong** [comment]
Ok I think I understand how we would add NaN support if it was needed.  But I think you can use an alternative approach.  As I mentioned above:

> Another option is to us a SparseTensor, as can be produced by a `ListColumnRepresentation`, and then use `scale_to_z_score` on the `SparseTensor`. See the handling of `OPTIONAL_NUMERIC_FEATURE_KEYS` in https://github.com/tensorflow/transform/blob/master/examples/census_example.py.

Can you take a look at this example and see if you could follow a similar pattern?

**Comment by harshini-gadige** [comment]
@baxen  - Hi, is this still an issue ? The alternate workaround suggested by Kester worked for you ?
Feel free to add your comments/close this issue if it no longer exists. Thank you !

**Comment by baxen** [comment]
Thanks for the suggestion - this sparse version does give the correct results:

```python
import tempfile
import tensorflow as tf
import numpy as np
import tensorflow_transform as tft
import tensorflow_transform.beam.impl as beam_impl
from tensorflow_transform.tf_metadata import dataset_metadata
from tensorflow_transform.tf_metadata import dataset_schema

size = 10000
values = np.random.normal(10.0, 10.0, size=size) # original has a mean of 10 and std of 10
values[np.random.rand(size) < 0.2] = np.nan  # but 20% have NaN


def preprocessing_fn(inputs):
    """Preprocess input columns into transformed columns."""
    x = inputs['x']
    x_zscore = tft.scale_to_z_score(x)
    x_zscore = tf.sparse_to_dense(
        x_zscore.indices,
        [x_zscore.dense_shape[0], 1],
        x_zscore.values,
        default_value=0.
    )
    return {
        'x_zscore': x_zscore,
     }

raw_data = [{'x': ([v] if not np.isnan(v) else [])} for v in values]
raw_data_spec = {'x': tf.VarLenFeature(tf.float32)}
raw_data_metadata = dataset_metadata.DatasetMetadata(
    dataset_schema.from_feature_spec(raw_data_spec)
)

with beam_impl.Context(temp_dir=tempfile.mkdtemp()):
    transformed_dataset, transform_fn = (
        (raw_data, raw_data_metadata) | beam_impl.AnalyzeAndTransformDataset(preprocessing_fn)
    )
    transformed_data, transformed_metadata = transformed_dataset  # pylint: disable=unused-variable
transformed = np.vstack(d['x_zscore'] for d in transformed_data)

print transformed.mean()
print transformed[transformed != 0].mean()
print transformed[transformed != 0].std()
```

I have not yet had a chance to test this in a large scale pipeline, any ideas if this will be similarly performant in the regime of many examples and many such features? 

For example one of our use cases has ~500 features that potentially have NaNs like this, and in the past we have concatenated them into a single 2D tensor and used `scale_to_z_score` with `elementwise=True`. If I understand correctly this would require ~500 sparse tensors which are not sparse in the traditional sense - they would typically have 80%+ values filled.

**Comment by KesterTong** [comment]
You can continue to use the optimization of combining your features into a single tensor and using `elementwise=True`.  You will need different code to concatenate your `SparseTensor`s into a single `SparseTensor`.  The code for handling missing data at https://github.com/tensorflow/transform/blob/master/examples/census_example.py#L138 may be useful as a reference
