### ISSUE TITLE
Can tf.transform handle viewfs:// path?

### ISSUE THREAD

**Issue by ShangzhiH** [tensorflow/transform#81]
I find after apache beam 2.5.0, the hdfs path can be recognized by beam's python sdk.
But in "/python2.7/site-packages/apache_beam/io/hadoopfilesystem.py", the support schema is only "hdfs". When i loaded a viewfs path, i got this error:

![image](https://user-images.githubusercontent.com/10820168/46090144-aaf8c580-c1e2-11e8-9ae6-540bb4747dd3.png)

Could anyone give me some advice about use tf.transform to read an file in viewfs filesystem, i really appreciate it.
Thank you!

**Comment by hgadig** [comment]
Request you to post this issue in Apache Beam's jira as this is more related to it. Thanks!
