### ISSUE TITLE
Beam WriteTransformFn leads to RuntimeError: AlreadyExistsError: file already exists

### ISSUE THREAD

**Issue by ozgurdemir** [tensorflow/transform#86]
Hi,

while writing out the transformation function:

`(transform_fn | 'WriteTransformFn' >> WriteTransformFn(tft_dir))`

we get the following error:

`RuntimeError: AlreadyExistsError: file already exists [while running 'WriteTransformFn/WriteTransformFn']`

It seems that multiple saved_model.pb files are generated in the tft-beam.Context tmp dir. WriteTransformFn then tries to copy them leading to above error.

Tensorflow: 1.9.0
Tensorflow Transform: 0.9.0
Apache Beam: 2.6.0

**Comment by zeevikal** [comment]
Hi,
I'm getting the same error while running it with dataflow runner.
@ozgurdemir if you're using so, please try to replace `saved_model.pb` dir to `/tmp` (worker temp path) instead of using GCS.
BTW - @harshini-gadige please let us know when it will be fixed, and if I can help with it.
best.

**Comment by ozgurdemir** [comment]
@zeevikal Thanks for the reply. Funny enough I can't reproduce the error anymore. I was broken locally. Now it's running locally and on dataflow.

**Comment by zeevikal** [comment]
@ozgurdemir hey, how you solve it?
for me, it's running perfectly locally but keep crashing on Dataflow (few workers).

**Comment by ozgurdemir** [comment]
@zeevikal As said unfortunately I don't have the old code anymore. Could you maybe share some code snippet. I could  then compare with what I have and try to spot differences.

**Comment by ozgurdemir** [comment]
@zeevikal do you still have this problem? I'm gonna close this issue otherwise.

**Comment by zeevikal** [comment]
@ozgurdemir you can close this issue. thanks.

**Comment by bartcode** [comment]
This might be a little too late, but for anyone who's running into this:
When you're using something similar to the code below:
```python
with beam.Pipeline(options=pipeline_options) as pipeline:
      # Do stuff
      pass
```
Make sure you're not using `pipeline.run()`. Otherwise, it will run the pipeline twice, causing the `AlreadyExistsError`.
