### ISSUE TITLE
Add tensorflow_transform.__version__

### ISSUE THREAD

**Issue by brianmartin** [tensorflow/transform#94]
Hi! For running Dataflow jobs it is sometimes required for us to ensure that Dataflow workers have certain required packages installed. For this reason, it would be useful to be able to determine the `tensorflow_transform` version at runtime.

Ideally, this would follow the common python convention of a `__version__` in the top-level module. For example, how `tensorflow-data-validation` does:

```
In [1]: import tensorflow_data_validation
In [2]: tensorflow_data_validation.__version__
Out[2]: '0.11.0'
```

**Comment by brianmartin** [comment]
Hey @zoyahav, let me know how I can help here. This would be really useful for us. 

I would submit a PR to add the `__version__` var, but this could easily become out of date unless it's handled by the release process (which I don't see much trace of in this repo).

**Comment by zoyahav** [comment]
Thanks @brianmartin, assigning to you since you have a pending PR fixing this.
