### ISSUE TITLE
Support for (weighted) N-hot encoder

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/transform#95]
I am working on a use case where we have a categorical feature associated with a weight. We would like to transform it to a "weighted N-Hot encoder". The use case is the following: 
In the field of music taste, we have a feature called "genre affinities".
For one example, it could look like this:
```json
{
"rock": 0.75,
"pop": 0.12,
"rap": 0.88
}
```
There could be a variable number of entries (possibly 0).

The "vocabulary" of possible keys/genres is not explicitly known beforehand.
We would like a set of analyzer and transformer to compute the vocabulary of possible keys and then build a SparseVector that would represent this N-hot encoded feature with the weights instead of ones. Expected output would look like this:

With the previous example and another presented this way:
```json
{
"rock": 0.13,
"latin": 0.96,
"k-pop": 0.76,
"country": 0.08
}
```
then an analyzed and transformed batch of these would give:
```python
tf.SparseVector(
    indices = [[0, 0], [0, 4], [0, 5], [1, 0], [1, 1], [1, 2], [1, 3]],
    values = [0.75, 0.12, 0.88, 0.13, 0.96, 0.76, 0.08], 
    dense_shape = [2, 6])
```

We're not sure yet how to build a `tf.Example` to present the input yet, since this transformation does not exist at all yet.
Any ideas of how that could be done?

A basic N-Hot encoder would be great to have as well (same thing but with only ones the weights in the values).

**Comment by KesterTong** [comment]
The best approach right now is the encode both weights and category indices as separate `VarLenFeature`s.  See https://github.com/tensorflow/transform/blob/master/examples/sentiment_example.py for an example of this.

It may be a while before we have better native support for `SparseFeature` in Transform.

**Comment by hgadig** [comment]
Closing as this is answered.
