### ISSUE TITLE
quatile_ops is from tf.contrib and explicitly loading is required in model serving

### ISSUE THREAD

**Issue by daikeshi** [tensorflow/transform#98]
When we use `bucketize` transformation, it calls `quatile_ops` from `tensorflow.contrib.boosted_trees.python.ops` module.  Since it's from `tf.contrib` module, We have to explicitly load the shared library during the model serving. 

It's probably OK in python as we only need to add an extra `import` statement. However, we are doing model serving in JVM, in java we'll have to find the path to the shared object file `_boosted_trees_ops.so` and explicitly load it using `TensorFlow.loadLibrary("/path/to/_boosted_trees_ops.so")`. This is really annoying since the `.so` file is system dependent.  

TFT is officially supported in model serving and one of the biggest benefits of using TFT is to simplify the model serving. We wonder if you guys consider moving `quatile_ops` into the standard tensorflow lib, so we don't need to explicitly locate and load the share library file when we are serving the model in JVM.

Thanks a lot!

**Comment by zoyahav** [comment]
We will be working on this as part of tensorflow-transform's TF 2.0 support work.
